// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cyber-ecosystem/app/services/system/internal/ent/permissionpolicy"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PermissionPolicy is the model entity for the PermissionPolicy schema.
type PermissionPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// tenant scope; back-filled on insert and filtered from the request subject
	TenantID string `json:"tenant_id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID string `json:"permission_id,omitempty"`
	// PolicyID holds the value of the "policy_id" field.
	PolicyID     string `json:"policy_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PermissionPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case permissionpolicy.FieldID, permissionpolicy.FieldTenantID, permissionpolicy.FieldPermissionID, permissionpolicy.FieldPolicyID:
			values[i] = new(sql.NullString)
		case permissionpolicy.FieldCreatedAt, permissionpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PermissionPolicy fields.
func (_m *PermissionPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permissionpolicy.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case permissionpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case permissionpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case permissionpolicy.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case permissionpolicy.FieldPermissionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = value.String
			}
		case permissionpolicy.FieldPolicyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field policy_id", values[i])
			} else if value.Valid {
				_m.PolicyID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PermissionPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *PermissionPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PermissionPolicy.
// Note that you need to call PermissionPolicy.Unwrap() before calling this method if this PermissionPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PermissionPolicy) Update() *PermissionPolicyUpdateOne {
	return NewPermissionPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PermissionPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PermissionPolicy) Unwrap() *PermissionPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PermissionPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PermissionPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("PermissionPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(_m.PermissionID)
	builder.WriteString(", ")
	builder.WriteString("policy_id=")
	builder.WriteString(_m.PolicyID)
	builder.WriteByte(')')
	return builder.String()
}

// PermissionPolicies is a parsable slice of PermissionPolicy.
type PermissionPolicies []*PermissionPolicy
