// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyber-ecosystem/app/services/system/internal/ent/permission"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PermissionCreate is the builder for creating a Permission entity.
type PermissionCreate struct {
	config
	mutation *PermissionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PermissionCreate) SetCreatedAt(v time.Time) *PermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableCreatedAt(v *time.Time) *PermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PermissionCreate) SetUpdatedAt(v time.Time) *PermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableUpdatedAt(v *time.Time) *PermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PermissionCreate) SetTenantID(v string) *PermissionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *PermissionCreate) SetRoleID(v string) *PermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *PermissionCreate) SetOperation(v string) *PermissionCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetEffect sets the "effect" field.
func (_c *PermissionCreate) SetEffect(v string) *PermissionCreate {
	_c.mutation.SetEffect(v)
	return _c
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableEffect(v *string) *PermissionCreate {
	if v != nil {
		_c.SetEffect(*v)
	}
	return _c
}

// SetScopeKind sets the "scope_kind" field.
func (_c *PermissionCreate) SetScopeKind(v string) *PermissionCreate {
	_c.mutation.SetScopeKind(v)
	return _c
}

// SetNillableScopeKind sets the "scope_kind" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableScopeKind(v *string) *PermissionCreate {
	if v != nil {
		_c.SetScopeKind(*v)
	}
	return _c
}

// SetScopeParams sets the "scope_params" field.
func (_c *PermissionCreate) SetScopeParams(v map[string]interface{}) *PermissionCreate {
	_c.mutation.SetScopeParams(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionCreate) SetID(v string) *PermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableID(v *string) *PermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PermissionMutation object of the builder.
func (_c *PermissionCreate) Mutation() *PermissionMutation {
	return _c.mutation
}

// Save creates the Permission in the database.
func (_c *PermissionCreate) Save(ctx context.Context) (*Permission, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionCreate) SaveX(ctx context.Context) *Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if permission.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized permission.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := permission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if permission.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized permission.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := permission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Effect(); !ok {
		v := permission.DefaultEffect
		_c.mutation.SetEffect(v)
	}
	if _, ok := _c.mutation.ScopeKind(); !ok {
		v := permission.DefaultScopeKind
		_c.mutation.SetScopeKind(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if permission.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized permission.DefaultID (forgotten import ent/runtime?)")
		}
		v := permission.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Permission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Permission.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Permission.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := permission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Permission.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "Permission.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := permission.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "Permission.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "Permission.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := permission.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Permission.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Effect(); !ok {
		return &ValidationError{Name: "effect", err: errors.New(`ent: missing required field "Permission.effect"`)}
	}
	if v, ok := _c.mutation.Effect(); ok {
		if err := permission.EffectValidator(v); err != nil {
			return &ValidationError{Name: "effect", err: fmt.Errorf(`ent: validator failed for field "Permission.effect": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeKind(); !ok {
		return &ValidationError{Name: "scope_kind", err: errors.New(`ent: missing required field "Permission.scope_kind"`)}
	}
	if v, ok := _c.mutation.ScopeKind(); ok {
		if err := permission.ScopeKindValidator(v); err != nil {
			return &ValidationError{Name: "scope_kind", err: fmt.Errorf(`ent: validator failed for field "Permission.scope_kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := permission.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Permission.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PermissionCreate) sqlSave(ctx context.Context) (*Permission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Permission.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionCreate) createSpec() (*Permission, *sqlgraph.CreateSpec) {
	var (
		_node = &Permission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permission.Table, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(permission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(permission.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(permission.FieldRoleID, field.TypeString, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(permission.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Effect(); ok {
		_spec.SetField(permission.FieldEffect, field.TypeString, value)
		_node.Effect = value
	}
	if value, ok := _c.mutation.ScopeKind(); ok {
		_spec.SetField(permission.FieldScopeKind, field.TypeString, value)
		_node.ScopeKind = value
	}
	if value, ok := _c.mutation.ScopeParams(); ok {
		_spec.SetField(permission.FieldScopeParams, field.TypeJSON, value)
		_node.ScopeParams = value
	}
	return _node, _spec
}

// PermissionCreateBulk is the builder for creating many Permission entities in bulk.
type PermissionCreateBulk struct {
	config
	err      error
	builders []*PermissionCreate
}

// Save creates the Permission entities in the database.
func (_c *PermissionCreateBulk) Save(ctx context.Context) ([]*Permission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Permission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionCreateBulk) SaveX(ctx context.Context) []*Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
