apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db/namespace.yaml
  - db/postgresql.yaml
  - db/redis.yaml
  - storage/namespace.yaml
  - storage/seaweedfs.yaml
  - mq/namespace.yaml
  - mq/nats.yaml
  - realtime/namespace.yaml
  - realtime/centrifugo.yaml
  - media/namespace.yaml
  - media/livekit.yaml
  - observability/namespace.yaml
  - observability/clickhouse.yaml
  - observability/signoz-migrator.yaml
  - observability/signoz.yaml
  - observability/glitchtip.yaml
