// Code generated by ent, DO NOT EDIT.

package policyrule

import (
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Ptype applies equality check predicate on the "ptype" field. It's identical to PtypeEQ.
func Ptype(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldPtype, v))
}

// V0 applies equality check predicate on the "v0" field. It's identical to V0EQ.
func V0(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV0, v))
}

// V1 applies equality check predicate on the "v1" field. It's identical to V1EQ.
func V1(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV1, v))
}

// V2 applies equality check predicate on the "v2" field. It's identical to V2EQ.
func V2(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV2, v))
}

// V3 applies equality check predicate on the "v3" field. It's identical to V3EQ.
func V3(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV3, v))
}

// V4 applies equality check predicate on the "v4" field. It's identical to V4EQ.
func V4(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV4, v))
}

// V5 applies equality check predicate on the "v5" field. It's identical to V5EQ.
func V5(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV5, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// PtypeEQ applies the EQ predicate on the "ptype" field.
func PtypeEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldPtype, v))
}

// PtypeNEQ applies the NEQ predicate on the "ptype" field.
func PtypeNEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldPtype, v))
}

// PtypeIn applies the In predicate on the "ptype" field.
func PtypeIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldPtype, vs...))
}

// PtypeNotIn applies the NotIn predicate on the "ptype" field.
func PtypeNotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldPtype, vs...))
}

// PtypeGT applies the GT predicate on the "ptype" field.
func PtypeGT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldPtype, v))
}

// PtypeGTE applies the GTE predicate on the "ptype" field.
func PtypeGTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldPtype, v))
}

// PtypeLT applies the LT predicate on the "ptype" field.
func PtypeLT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldPtype, v))
}

// PtypeLTE applies the LTE predicate on the "ptype" field.
func PtypeLTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldPtype, v))
}

// PtypeContains applies the Contains predicate on the "ptype" field.
func PtypeContains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldPtype, v))
}

// PtypeHasPrefix applies the HasPrefix predicate on the "ptype" field.
func PtypeHasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldPtype, v))
}

// PtypeHasSuffix applies the HasSuffix predicate on the "ptype" field.
func PtypeHasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldPtype, v))
}

// PtypeEqualFold applies the EqualFold predicate on the "ptype" field.
func PtypeEqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldPtype, v))
}

// PtypeContainsFold applies the ContainsFold predicate on the "ptype" field.
func PtypeContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldPtype, v))
}

// V0EQ applies the EQ predicate on the "v0" field.
func V0EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV0, v))
}

// V0NEQ applies the NEQ predicate on the "v0" field.
func V0NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV0, v))
}

// V0In applies the In predicate on the "v0" field.
func V0In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV0, vs...))
}

// V0NotIn applies the NotIn predicate on the "v0" field.
func V0NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV0, vs...))
}

// V0GT applies the GT predicate on the "v0" field.
func V0GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV0, v))
}

// V0GTE applies the GTE predicate on the "v0" field.
func V0GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV0, v))
}

// V0LT applies the LT predicate on the "v0" field.
func V0LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV0, v))
}

// V0LTE applies the LTE predicate on the "v0" field.
func V0LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV0, v))
}

// V0Contains applies the Contains predicate on the "v0" field.
func V0Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV0, v))
}

// V0HasPrefix applies the HasPrefix predicate on the "v0" field.
func V0HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV0, v))
}

// V0HasSuffix applies the HasSuffix predicate on the "v0" field.
func V0HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV0, v))
}

// V0IsNil applies the IsNil predicate on the "v0" field.
func V0IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV0))
}

// V0NotNil applies the NotNil predicate on the "v0" field.
func V0NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV0))
}

// V0EqualFold applies the EqualFold predicate on the "v0" field.
func V0EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV0, v))
}

// V0ContainsFold applies the ContainsFold predicate on the "v0" field.
func V0ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV0, v))
}

// V1EQ applies the EQ predicate on the "v1" field.
func V1EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV1, v))
}

// V1NEQ applies the NEQ predicate on the "v1" field.
func V1NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV1, v))
}

// V1In applies the In predicate on the "v1" field.
func V1In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV1, vs...))
}

// V1NotIn applies the NotIn predicate on the "v1" field.
func V1NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV1, vs...))
}

// V1GT applies the GT predicate on the "v1" field.
func V1GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV1, v))
}

// V1GTE applies the GTE predicate on the "v1" field.
func V1GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV1, v))
}

// V1LT applies the LT predicate on the "v1" field.
func V1LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV1, v))
}

// V1LTE applies the LTE predicate on the "v1" field.
func V1LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV1, v))
}

// V1Contains applies the Contains predicate on the "v1" field.
func V1Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV1, v))
}

// V1HasPrefix applies the HasPrefix predicate on the "v1" field.
func V1HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV1, v))
}

// V1HasSuffix applies the HasSuffix predicate on the "v1" field.
func V1HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV1, v))
}

// V1IsNil applies the IsNil predicate on the "v1" field.
func V1IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV1))
}

// V1NotNil applies the NotNil predicate on the "v1" field.
func V1NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV1))
}

// V1EqualFold applies the EqualFold predicate on the "v1" field.
func V1EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV1, v))
}

// V1ContainsFold applies the ContainsFold predicate on the "v1" field.
func V1ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV1, v))
}

// V2EQ applies the EQ predicate on the "v2" field.
func V2EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV2, v))
}

// V2NEQ applies the NEQ predicate on the "v2" field.
func V2NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV2, v))
}

// V2In applies the In predicate on the "v2" field.
func V2In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV2, vs...))
}

// V2NotIn applies the NotIn predicate on the "v2" field.
func V2NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV2, vs...))
}

// V2GT applies the GT predicate on the "v2" field.
func V2GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV2, v))
}

// V2GTE applies the GTE predicate on the "v2" field.
func V2GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV2, v))
}

// V2LT applies the LT predicate on the "v2" field.
func V2LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV2, v))
}

// V2LTE applies the LTE predicate on the "v2" field.
func V2LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV2, v))
}

// V2Contains applies the Contains predicate on the "v2" field.
func V2Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV2, v))
}

// V2HasPrefix applies the HasPrefix predicate on the "v2" field.
func V2HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV2, v))
}

// V2HasSuffix applies the HasSuffix predicate on the "v2" field.
func V2HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV2, v))
}

// V2IsNil applies the IsNil predicate on the "v2" field.
func V2IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV2))
}

// V2NotNil applies the NotNil predicate on the "v2" field.
func V2NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV2))
}

// V2EqualFold applies the EqualFold predicate on the "v2" field.
func V2EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV2, v))
}

// V2ContainsFold applies the ContainsFold predicate on the "v2" field.
func V2ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV2, v))
}

// V3EQ applies the EQ predicate on the "v3" field.
func V3EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV3, v))
}

// V3NEQ applies the NEQ predicate on the "v3" field.
func V3NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV3, v))
}

// V3In applies the In predicate on the "v3" field.
func V3In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV3, vs...))
}

// V3NotIn applies the NotIn predicate on the "v3" field.
func V3NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV3, vs...))
}

// V3GT applies the GT predicate on the "v3" field.
func V3GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV3, v))
}

// V3GTE applies the GTE predicate on the "v3" field.
func V3GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV3, v))
}

// V3LT applies the LT predicate on the "v3" field.
func V3LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV3, v))
}

// V3LTE applies the LTE predicate on the "v3" field.
func V3LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV3, v))
}

// V3Contains applies the Contains predicate on the "v3" field.
func V3Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV3, v))
}

// V3HasPrefix applies the HasPrefix predicate on the "v3" field.
func V3HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV3, v))
}

// V3HasSuffix applies the HasSuffix predicate on the "v3" field.
func V3HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV3, v))
}

// V3IsNil applies the IsNil predicate on the "v3" field.
func V3IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV3))
}

// V3NotNil applies the NotNil predicate on the "v3" field.
func V3NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV3))
}

// V3EqualFold applies the EqualFold predicate on the "v3" field.
func V3EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV3, v))
}

// V3ContainsFold applies the ContainsFold predicate on the "v3" field.
func V3ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV3, v))
}

// V4EQ applies the EQ predicate on the "v4" field.
func V4EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV4, v))
}

// V4NEQ applies the NEQ predicate on the "v4" field.
func V4NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV4, v))
}

// V4In applies the In predicate on the "v4" field.
func V4In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV4, vs...))
}

// V4NotIn applies the NotIn predicate on the "v4" field.
func V4NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV4, vs...))
}

// V4GT applies the GT predicate on the "v4" field.
func V4GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV4, v))
}

// V4GTE applies the GTE predicate on the "v4" field.
func V4GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV4, v))
}

// V4LT applies the LT predicate on the "v4" field.
func V4LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV4, v))
}

// V4LTE applies the LTE predicate on the "v4" field.
func V4LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV4, v))
}

// V4Contains applies the Contains predicate on the "v4" field.
func V4Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV4, v))
}

// V4HasPrefix applies the HasPrefix predicate on the "v4" field.
func V4HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV4, v))
}

// V4HasSuffix applies the HasSuffix predicate on the "v4" field.
func V4HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV4, v))
}

// V4IsNil applies the IsNil predicate on the "v4" field.
func V4IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV4))
}

// V4NotNil applies the NotNil predicate on the "v4" field.
func V4NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV4))
}

// V4EqualFold applies the EqualFold predicate on the "v4" field.
func V4EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV4, v))
}

// V4ContainsFold applies the ContainsFold predicate on the "v4" field.
func V4ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV4, v))
}

// V5EQ applies the EQ predicate on the "v5" field.
func V5EQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEQ(FieldV5, v))
}

// V5NEQ applies the NEQ predicate on the "v5" field.
func V5NEQ(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNEQ(FieldV5, v))
}

// V5In applies the In predicate on the "v5" field.
func V5In(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIn(FieldV5, vs...))
}

// V5NotIn applies the NotIn predicate on the "v5" field.
func V5NotIn(vs ...string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotIn(FieldV5, vs...))
}

// V5GT applies the GT predicate on the "v5" field.
func V5GT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGT(FieldV5, v))
}

// V5GTE applies the GTE predicate on the "v5" field.
func V5GTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldGTE(FieldV5, v))
}

// V5LT applies the LT predicate on the "v5" field.
func V5LT(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLT(FieldV5, v))
}

// V5LTE applies the LTE predicate on the "v5" field.
func V5LTE(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldLTE(FieldV5, v))
}

// V5Contains applies the Contains predicate on the "v5" field.
func V5Contains(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContains(FieldV5, v))
}

// V5HasPrefix applies the HasPrefix predicate on the "v5" field.
func V5HasPrefix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasPrefix(FieldV5, v))
}

// V5HasSuffix applies the HasSuffix predicate on the "v5" field.
func V5HasSuffix(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldHasSuffix(FieldV5, v))
}

// V5IsNil applies the IsNil predicate on the "v5" field.
func V5IsNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldIsNull(FieldV5))
}

// V5NotNil applies the NotNil predicate on the "v5" field.
func V5NotNil() predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldNotNull(FieldV5))
}

// V5EqualFold applies the EqualFold predicate on the "v5" field.
func V5EqualFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldEqualFold(FieldV5, v))
}

// V5ContainsFold applies the ContainsFold predicate on the "v5" field.
func V5ContainsFold(v string) predicate.PolicyRule {
	return predicate.PolicyRule(sql.FieldContainsFold(FieldV5, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PolicyRule) predicate.PolicyRule {
	return predicate.PolicyRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PolicyRule) predicate.PolicyRule {
	return predicate.PolicyRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PolicyRule) predicate.PolicyRule {
	return predicate.PolicyRule(sql.NotPredicates(p))
}
