// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file template/api/v1/resource.proto (package api.template.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_desc_desc } from "../../../desc/desc_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file template/api/v1/resource.proto.
 */
export const file_template_api_v1_resource: GenFile = /*@__PURE__*/
  fileDesc("Ch50ZW1wbGF0ZS9hcGkvdjEvcmVzb3VyY2UucHJvdG8SD2FwaS50ZW1wbGF0ZS52MSIVChNMaXN0UmVzb3VyY2VSZXF1ZXN0Ij4KFExpc3RSZXNvdXJjZVJlc3BvbnNlEiYKBGxpc3QYASADKAsyGC5hcGkudGVtcGxhdGUudjEuU2VydmljZSLGAQoGTWV0aG9kEgwKBG5hbWUYASABKAkSEQoJZnVsbF9uYW1lGAIgASgJEhQKDHJlcXVlc3RfbmFtZRgDIAEoCRIZChFyZXF1ZXN0X2Z1bGxfbmFtZRgEIAEoCRIVCg1yZXNwb25zZV9uYW1lGAUgASgJEhoKEnJlc3BvbnNlX2Z1bGxfbmFtZRgGIAEoCRITCgtodHRwX21ldGhvZBgHIAEoCRIRCglodHRwX3BhdGgYCCABKAkSDwoHY29tbWVudBgJIAEoCSKLAQoHU2VydmljZRIMCgRuYW1lGAEgASgJEhEKCWZ1bGxfbmFtZRgCIAEoCRIPCgdwYWNrYWdlGAMgASgJEhMKC3NvdXJjZV9maWxlGAQgASgJEg8KB2NvbW1lbnQYBSABKAkSKAoHbWV0aG9kcxgGIAMoCzIXLmFwaS50ZW1wbGF0ZS52MS5NZXRob2QyugEKD1Jlc291cmNlU2VydmljZRKOAQoMTGlzdFJlc291cmNlEiQuYXBpLnRlbXBsYXRlLnYxLkxpc3RSZXNvdXJjZVJlcXVlc3QaJS5hcGkudGVtcGxhdGUudjEuTGlzdFJlc291cmNlUmVzcG9uc2UiMYrTDhXojrflj5bmiYDmnIlycGPkv6Hmga+C0+STAhISEC9hcGkvdjEvcmVzb3VyY2UaForiCRLns7vnu5/otYTmupDmnI3liqFCNFoyY3liZXItZWNvc3lzdGVtL2FwcHMvdGVtcGxhdGUvZ2VuL2dvL3YxO3RlbXBsYXRlVjFiBnByb3RvMw", [file_desc_desc, file_google_api_annotations]);

/**
 * @generated from message api.template.v1.ListResourceRequest
 */
export type ListResourceRequest = Message<"api.template.v1.ListResourceRequest"> & {
};

/**
 * Describes the message api.template.v1.ListResourceRequest.
 * Use `create(ListResourceRequestSchema)` to create a new message.
 */
export const ListResourceRequestSchema: GenMessage<ListResourceRequest> = /*@__PURE__*/
  messageDesc(file_template_api_v1_resource, 0);

/**
 * @generated from message api.template.v1.ListResourceResponse
 */
export type ListResourceResponse = Message<"api.template.v1.ListResourceResponse"> & {
  /**
   * @generated from field: repeated api.template.v1.Service list = 1;
   */
  list: Service[];
};

/**
 * Describes the message api.template.v1.ListResourceResponse.
 * Use `create(ListResourceResponseSchema)` to create a new message.
 */
export const ListResourceResponseSchema: GenMessage<ListResourceResponse> = /*@__PURE__*/
  messageDesc(file_template_api_v1_resource, 1);

/**
 * @generated from message api.template.v1.Method
 */
export type Method = Message<"api.template.v1.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string full_name = 2;
   */
  fullName: string;

  /**
   * @generated from field: string request_name = 3;
   */
  requestName: string;

  /**
   * @generated from field: string request_full_name = 4;
   */
  requestFullName: string;

  /**
   * @generated from field: string response_name = 5;
   */
  responseName: string;

  /**
   * @generated from field: string response_full_name = 6;
   */
  responseFullName: string;

  /**
   * @generated from field: string http_method = 7;
   */
  httpMethod: string;

  /**
   * @generated from field: string http_path = 8;
   */
  httpPath: string;

  /**
   * @generated from field: string comment = 9;
   */
  comment: string;
};

/**
 * Describes the message api.template.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export const MethodSchema: GenMessage<Method> = /*@__PURE__*/
  messageDesc(file_template_api_v1_resource, 2);

/**
 * @generated from message api.template.v1.Service
 */
export type Service = Message<"api.template.v1.Service"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string full_name = 2;
   */
  fullName: string;

  /**
   * @generated from field: string package = 3;
   */
  package: string;

  /**
   * @generated from field: string source_file = 4;
   */
  sourceFile: string;

  /**
   * @generated from field: string comment = 5;
   */
  comment: string;

  /**
   * @generated from field: repeated api.template.v1.Method methods = 6;
   */
  methods: Method[];
};

/**
 * Describes the message api.template.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export const ServiceSchema: GenMessage<Service> = /*@__PURE__*/
  messageDesc(file_template_api_v1_resource, 3);

/**
 * ResourceService
 *
 * @generated from service api.template.v1.ResourceService
 */
export const ResourceService: GenService<{
  /**
   * ListResource
   *
   * @generated from rpc api.template.v1.ResourceService.ListResource
   */
  listResource: {
    methodKind: "unary";
    input: typeof ListResourceRequestSchema;
    output: typeof ListResourceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_template_api_v1_resource, 0);

