// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/migrate"

	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/condition"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/datascope"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/department"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/policyrule"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/role"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/user"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/userattribute"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/workreport"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Condition is the client for interacting with the Condition builders.
	Condition *ConditionClient
	// DataScope is the client for interacting with the DataScope builders.
	DataScope *DataScopeClient
	// Department is the client for interacting with the Department builders.
	Department *DepartmentClient
	// PolicyRule is the client for interacting with the PolicyRule builders.
	PolicyRule *PolicyRuleClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserAttribute is the client for interacting with the UserAttribute builders.
	UserAttribute *UserAttributeClient
	// WorkReport is the client for interacting with the WorkReport builders.
	WorkReport *WorkReportClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Condition = NewConditionClient(c.config)
	c.DataScope = NewDataScopeClient(c.config)
	c.Department = NewDepartmentClient(c.config)
	c.PolicyRule = NewPolicyRuleClient(c.config)
	c.Role = NewRoleClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserAttribute = NewUserAttributeClient(c.config)
	c.WorkReport = NewWorkReportClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Condition:     NewConditionClient(cfg),
		DataScope:     NewDataScopeClient(cfg),
		Department:    NewDepartmentClient(cfg),
		PolicyRule:    NewPolicyRuleClient(cfg),
		Role:          NewRoleClient(cfg),
		User:          NewUserClient(cfg),
		UserAttribute: NewUserAttributeClient(cfg),
		WorkReport:    NewWorkReportClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Condition:     NewConditionClient(cfg),
		DataScope:     NewDataScopeClient(cfg),
		Department:    NewDepartmentClient(cfg),
		PolicyRule:    NewPolicyRuleClient(cfg),
		Role:          NewRoleClient(cfg),
		User:          NewUserClient(cfg),
		UserAttribute: NewUserAttributeClient(cfg),
		WorkReport:    NewWorkReportClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Condition.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Condition, c.DataScope, c.Department, c.PolicyRule, c.Role, c.User,
		c.UserAttribute, c.WorkReport,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Condition, c.DataScope, c.Department, c.PolicyRule, c.Role, c.User,
		c.UserAttribute, c.WorkReport,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ConditionMutation:
		return c.Condition.mutate(ctx, m)
	case *DataScopeMutation:
		return c.DataScope.mutate(ctx, m)
	case *DepartmentMutation:
		return c.Department.mutate(ctx, m)
	case *PolicyRuleMutation:
		return c.PolicyRule.mutate(ctx, m)
	case *RoleMutation:
		return c.Role.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserAttributeMutation:
		return c.UserAttribute.mutate(ctx, m)
	case *WorkReportMutation:
		return c.WorkReport.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ConditionClient is a client for the Condition schema.
type ConditionClient struct {
	config
}

// NewConditionClient returns a client for the Condition from the given config.
func NewConditionClient(c config) *ConditionClient {
	return &ConditionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `condition.Hooks(f(g(h())))`.
func (c *ConditionClient) Use(hooks ...Hook) {
	c.hooks.Condition = append(c.hooks.Condition, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `condition.Intercept(f(g(h())))`.
func (c *ConditionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Condition = append(c.inters.Condition, interceptors...)
}

// Create returns a builder for creating a Condition entity.
func (c *ConditionClient) Create() *ConditionCreate {
	mutation := newConditionMutation(c.config, OpCreate)
	return &ConditionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Condition entities.
func (c *ConditionClient) CreateBulk(builders ...*ConditionCreate) *ConditionCreateBulk {
	return &ConditionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConditionClient) MapCreateBulk(slice any, setFunc func(*ConditionCreate, int)) *ConditionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConditionCreateBulk{err: fmt.Errorf("calling to ConditionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConditionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConditionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Condition.
func (c *ConditionClient) Update() *ConditionUpdate {
	mutation := newConditionMutation(c.config, OpUpdate)
	return &ConditionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConditionClient) UpdateOne(_m *Condition) *ConditionUpdateOne {
	mutation := newConditionMutation(c.config, OpUpdateOne, withCondition(_m))
	return &ConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConditionClient) UpdateOneID(id string) *ConditionUpdateOne {
	mutation := newConditionMutation(c.config, OpUpdateOne, withConditionID(id))
	return &ConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Condition.
func (c *ConditionClient) Delete() *ConditionDelete {
	mutation := newConditionMutation(c.config, OpDelete)
	return &ConditionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConditionClient) DeleteOne(_m *Condition) *ConditionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConditionClient) DeleteOneID(id string) *ConditionDeleteOne {
	builder := c.Delete().Where(condition.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConditionDeleteOne{builder}
}

// Query returns a query builder for Condition.
func (c *ConditionClient) Query() *ConditionQuery {
	return &ConditionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCondition},
		inters: c.Interceptors(),
	}
}

// Get returns a Condition entity by its id.
func (c *ConditionClient) Get(ctx context.Context, id string) (*Condition, error) {
	return c.Query().Where(condition.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConditionClient) GetX(ctx context.Context, id string) *Condition {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ConditionClient) Hooks() []Hook {
	return c.hooks.Condition
}

// Interceptors returns the client interceptors.
func (c *ConditionClient) Interceptors() []Interceptor {
	return c.inters.Condition
}

func (c *ConditionClient) mutate(ctx context.Context, m *ConditionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConditionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConditionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConditionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConditionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Condition mutation op: %q", m.Op())
	}
}

// DataScopeClient is a client for the DataScope schema.
type DataScopeClient struct {
	config
}

// NewDataScopeClient returns a client for the DataScope from the given config.
func NewDataScopeClient(c config) *DataScopeClient {
	return &DataScopeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `datascope.Hooks(f(g(h())))`.
func (c *DataScopeClient) Use(hooks ...Hook) {
	c.hooks.DataScope = append(c.hooks.DataScope, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `datascope.Intercept(f(g(h())))`.
func (c *DataScopeClient) Intercept(interceptors ...Interceptor) {
	c.inters.DataScope = append(c.inters.DataScope, interceptors...)
}

// Create returns a builder for creating a DataScope entity.
func (c *DataScopeClient) Create() *DataScopeCreate {
	mutation := newDataScopeMutation(c.config, OpCreate)
	return &DataScopeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DataScope entities.
func (c *DataScopeClient) CreateBulk(builders ...*DataScopeCreate) *DataScopeCreateBulk {
	return &DataScopeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DataScopeClient) MapCreateBulk(slice any, setFunc func(*DataScopeCreate, int)) *DataScopeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DataScopeCreateBulk{err: fmt.Errorf("calling to DataScopeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DataScopeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DataScopeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DataScope.
func (c *DataScopeClient) Update() *DataScopeUpdate {
	mutation := newDataScopeMutation(c.config, OpUpdate)
	return &DataScopeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DataScopeClient) UpdateOne(_m *DataScope) *DataScopeUpdateOne {
	mutation := newDataScopeMutation(c.config, OpUpdateOne, withDataScope(_m))
	return &DataScopeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DataScopeClient) UpdateOneID(id string) *DataScopeUpdateOne {
	mutation := newDataScopeMutation(c.config, OpUpdateOne, withDataScopeID(id))
	return &DataScopeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DataScope.
func (c *DataScopeClient) Delete() *DataScopeDelete {
	mutation := newDataScopeMutation(c.config, OpDelete)
	return &DataScopeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DataScopeClient) DeleteOne(_m *DataScope) *DataScopeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DataScopeClient) DeleteOneID(id string) *DataScopeDeleteOne {
	builder := c.Delete().Where(datascope.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DataScopeDeleteOne{builder}
}

// Query returns a query builder for DataScope.
func (c *DataScopeClient) Query() *DataScopeQuery {
	return &DataScopeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDataScope},
		inters: c.Interceptors(),
	}
}

// Get returns a DataScope entity by its id.
func (c *DataScopeClient) Get(ctx context.Context, id string) (*DataScope, error) {
	return c.Query().Where(datascope.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DataScopeClient) GetX(ctx context.Context, id string) *DataScope {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DataScopeClient) Hooks() []Hook {
	return c.hooks.DataScope
}

// Interceptors returns the client interceptors.
func (c *DataScopeClient) Interceptors() []Interceptor {
	return c.inters.DataScope
}

func (c *DataScopeClient) mutate(ctx context.Context, m *DataScopeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DataScopeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DataScopeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DataScopeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DataScopeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DataScope mutation op: %q", m.Op())
	}
}

// DepartmentClient is a client for the Department schema.
type DepartmentClient struct {
	config
}

// NewDepartmentClient returns a client for the Department from the given config.
func NewDepartmentClient(c config) *DepartmentClient {
	return &DepartmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `department.Hooks(f(g(h())))`.
func (c *DepartmentClient) Use(hooks ...Hook) {
	c.hooks.Department = append(c.hooks.Department, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `department.Intercept(f(g(h())))`.
func (c *DepartmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Department = append(c.inters.Department, interceptors...)
}

// Create returns a builder for creating a Department entity.
func (c *DepartmentClient) Create() *DepartmentCreate {
	mutation := newDepartmentMutation(c.config, OpCreate)
	return &DepartmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Department entities.
func (c *DepartmentClient) CreateBulk(builders ...*DepartmentCreate) *DepartmentCreateBulk {
	return &DepartmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepartmentClient) MapCreateBulk(slice any, setFunc func(*DepartmentCreate, int)) *DepartmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepartmentCreateBulk{err: fmt.Errorf("calling to DepartmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepartmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepartmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Department.
func (c *DepartmentClient) Update() *DepartmentUpdate {
	mutation := newDepartmentMutation(c.config, OpUpdate)
	return &DepartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepartmentClient) UpdateOne(_m *Department) *DepartmentUpdateOne {
	mutation := newDepartmentMutation(c.config, OpUpdateOne, withDepartment(_m))
	return &DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepartmentClient) UpdateOneID(id string) *DepartmentUpdateOne {
	mutation := newDepartmentMutation(c.config, OpUpdateOne, withDepartmentID(id))
	return &DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Department.
func (c *DepartmentClient) Delete() *DepartmentDelete {
	mutation := newDepartmentMutation(c.config, OpDelete)
	return &DepartmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepartmentClient) DeleteOne(_m *Department) *DepartmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepartmentClient) DeleteOneID(id string) *DepartmentDeleteOne {
	builder := c.Delete().Where(department.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepartmentDeleteOne{builder}
}

// Query returns a query builder for Department.
func (c *DepartmentClient) Query() *DepartmentQuery {
	return &DepartmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDepartment},
		inters: c.Interceptors(),
	}
}

// Get returns a Department entity by its id.
func (c *DepartmentClient) Get(ctx context.Context, id string) (*Department, error) {
	return c.Query().Where(department.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepartmentClient) GetX(ctx context.Context, id string) *Department {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Department.
func (c *DepartmentClient) QueryUsers(_m *Department) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(department.Table, department.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, department.UsersTable, department.UsersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DepartmentClient) Hooks() []Hook {
	return c.hooks.Department
}

// Interceptors returns the client interceptors.
func (c *DepartmentClient) Interceptors() []Interceptor {
	return c.inters.Department
}

func (c *DepartmentClient) mutate(ctx context.Context, m *DepartmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepartmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepartmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Department mutation op: %q", m.Op())
	}
}

// PolicyRuleClient is a client for the PolicyRule schema.
type PolicyRuleClient struct {
	config
}

// NewPolicyRuleClient returns a client for the PolicyRule from the given config.
func NewPolicyRuleClient(c config) *PolicyRuleClient {
	return &PolicyRuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `policyrule.Hooks(f(g(h())))`.
func (c *PolicyRuleClient) Use(hooks ...Hook) {
	c.hooks.PolicyRule = append(c.hooks.PolicyRule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `policyrule.Intercept(f(g(h())))`.
func (c *PolicyRuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.PolicyRule = append(c.inters.PolicyRule, interceptors...)
}

// Create returns a builder for creating a PolicyRule entity.
func (c *PolicyRuleClient) Create() *PolicyRuleCreate {
	mutation := newPolicyRuleMutation(c.config, OpCreate)
	return &PolicyRuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PolicyRule entities.
func (c *PolicyRuleClient) CreateBulk(builders ...*PolicyRuleCreate) *PolicyRuleCreateBulk {
	return &PolicyRuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PolicyRuleClient) MapCreateBulk(slice any, setFunc func(*PolicyRuleCreate, int)) *PolicyRuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PolicyRuleCreateBulk{err: fmt.Errorf("calling to PolicyRuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PolicyRuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PolicyRuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PolicyRule.
func (c *PolicyRuleClient) Update() *PolicyRuleUpdate {
	mutation := newPolicyRuleMutation(c.config, OpUpdate)
	return &PolicyRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PolicyRuleClient) UpdateOne(_m *PolicyRule) *PolicyRuleUpdateOne {
	mutation := newPolicyRuleMutation(c.config, OpUpdateOne, withPolicyRule(_m))
	return &PolicyRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PolicyRuleClient) UpdateOneID(id string) *PolicyRuleUpdateOne {
	mutation := newPolicyRuleMutation(c.config, OpUpdateOne, withPolicyRuleID(id))
	return &PolicyRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PolicyRule.
func (c *PolicyRuleClient) Delete() *PolicyRuleDelete {
	mutation := newPolicyRuleMutation(c.config, OpDelete)
	return &PolicyRuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PolicyRuleClient) DeleteOne(_m *PolicyRule) *PolicyRuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PolicyRuleClient) DeleteOneID(id string) *PolicyRuleDeleteOne {
	builder := c.Delete().Where(policyrule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PolicyRuleDeleteOne{builder}
}

// Query returns a query builder for PolicyRule.
func (c *PolicyRuleClient) Query() *PolicyRuleQuery {
	return &PolicyRuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolicyRule},
		inters: c.Interceptors(),
	}
}

// Get returns a PolicyRule entity by its id.
func (c *PolicyRuleClient) Get(ctx context.Context, id string) (*PolicyRule, error) {
	return c.Query().Where(policyrule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PolicyRuleClient) GetX(ctx context.Context, id string) *PolicyRule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PolicyRuleClient) Hooks() []Hook {
	return c.hooks.PolicyRule
}

// Interceptors returns the client interceptors.
func (c *PolicyRuleClient) Interceptors() []Interceptor {
	return c.inters.PolicyRule
}

func (c *PolicyRuleClient) mutate(ctx context.Context, m *PolicyRuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PolicyRuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PolicyRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PolicyRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PolicyRuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PolicyRule mutation op: %q", m.Op())
	}
}

// RoleClient is a client for the Role schema.
type RoleClient struct {
	config
}

// NewRoleClient returns a client for the Role from the given config.
func NewRoleClient(c config) *RoleClient {
	return &RoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `role.Hooks(f(g(h())))`.
func (c *RoleClient) Use(hooks ...Hook) {
	c.hooks.Role = append(c.hooks.Role, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `role.Intercept(f(g(h())))`.
func (c *RoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Role = append(c.inters.Role, interceptors...)
}

// Create returns a builder for creating a Role entity.
func (c *RoleClient) Create() *RoleCreate {
	mutation := newRoleMutation(c.config, OpCreate)
	return &RoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Role entities.
func (c *RoleClient) CreateBulk(builders ...*RoleCreate) *RoleCreateBulk {
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoleClient) MapCreateBulk(slice any, setFunc func(*RoleCreate, int)) *RoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoleCreateBulk{err: fmt.Errorf("calling to RoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Role.
func (c *RoleClient) Update() *RoleUpdate {
	mutation := newRoleMutation(c.config, OpUpdate)
	return &RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoleClient) UpdateOne(_m *Role) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRole(_m))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoleClient) UpdateOneID(id string) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRoleID(id))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Role.
func (c *RoleClient) Delete() *RoleDelete {
	mutation := newRoleMutation(c.config, OpDelete)
	return &RoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoleClient) DeleteOne(_m *Role) *RoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoleClient) DeleteOneID(id string) *RoleDeleteOne {
	builder := c.Delete().Where(role.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoleDeleteOne{builder}
}

// Query returns a query builder for Role.
func (c *RoleClient) Query() *RoleQuery {
	return &RoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRole},
		inters: c.Interceptors(),
	}
}

// Get returns a Role entity by its id.
func (c *RoleClient) Get(ctx context.Context, id string) (*Role, error) {
	return c.Query().Where(role.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoleClient) GetX(ctx context.Context, id string) *Role {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RoleClient) Hooks() []Hook {
	return c.hooks.Role
}

// Interceptors returns the client interceptors.
func (c *RoleClient) Interceptors() []Interceptor {
	return c.inters.Role
}

func (c *RoleClient) mutate(ctx context.Context, m *RoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Role mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDepartments queries the departments edge of a User.
func (c *UserClient) QueryDepartments(_m *User) *DepartmentQuery {
	query := (&DepartmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.DepartmentsTable, user.DepartmentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	inters := c.inters.User
	return append(inters[:len(inters):len(inters)], user.Interceptors[:]...)
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserAttributeClient is a client for the UserAttribute schema.
type UserAttributeClient struct {
	config
}

// NewUserAttributeClient returns a client for the UserAttribute from the given config.
func NewUserAttributeClient(c config) *UserAttributeClient {
	return &UserAttributeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userattribute.Hooks(f(g(h())))`.
func (c *UserAttributeClient) Use(hooks ...Hook) {
	c.hooks.UserAttribute = append(c.hooks.UserAttribute, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userattribute.Intercept(f(g(h())))`.
func (c *UserAttributeClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserAttribute = append(c.inters.UserAttribute, interceptors...)
}

// Create returns a builder for creating a UserAttribute entity.
func (c *UserAttributeClient) Create() *UserAttributeCreate {
	mutation := newUserAttributeMutation(c.config, OpCreate)
	return &UserAttributeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserAttribute entities.
func (c *UserAttributeClient) CreateBulk(builders ...*UserAttributeCreate) *UserAttributeCreateBulk {
	return &UserAttributeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserAttributeClient) MapCreateBulk(slice any, setFunc func(*UserAttributeCreate, int)) *UserAttributeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserAttributeCreateBulk{err: fmt.Errorf("calling to UserAttributeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserAttributeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserAttributeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserAttribute.
func (c *UserAttributeClient) Update() *UserAttributeUpdate {
	mutation := newUserAttributeMutation(c.config, OpUpdate)
	return &UserAttributeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserAttributeClient) UpdateOne(_m *UserAttribute) *UserAttributeUpdateOne {
	mutation := newUserAttributeMutation(c.config, OpUpdateOne, withUserAttribute(_m))
	return &UserAttributeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserAttributeClient) UpdateOneID(id string) *UserAttributeUpdateOne {
	mutation := newUserAttributeMutation(c.config, OpUpdateOne, withUserAttributeID(id))
	return &UserAttributeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserAttribute.
func (c *UserAttributeClient) Delete() *UserAttributeDelete {
	mutation := newUserAttributeMutation(c.config, OpDelete)
	return &UserAttributeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserAttributeClient) DeleteOne(_m *UserAttribute) *UserAttributeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserAttributeClient) DeleteOneID(id string) *UserAttributeDeleteOne {
	builder := c.Delete().Where(userattribute.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserAttributeDeleteOne{builder}
}

// Query returns a query builder for UserAttribute.
func (c *UserAttributeClient) Query() *UserAttributeQuery {
	return &UserAttributeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserAttribute},
		inters: c.Interceptors(),
	}
}

// Get returns a UserAttribute entity by its id.
func (c *UserAttributeClient) Get(ctx context.Context, id string) (*UserAttribute, error) {
	return c.Query().Where(userattribute.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserAttributeClient) GetX(ctx context.Context, id string) *UserAttribute {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserAttributeClient) Hooks() []Hook {
	return c.hooks.UserAttribute
}

// Interceptors returns the client interceptors.
func (c *UserAttributeClient) Interceptors() []Interceptor {
	return c.inters.UserAttribute
}

func (c *UserAttributeClient) mutate(ctx context.Context, m *UserAttributeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserAttributeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserAttributeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserAttributeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserAttributeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserAttribute mutation op: %q", m.Op())
	}
}

// WorkReportClient is a client for the WorkReport schema.
type WorkReportClient struct {
	config
}

// NewWorkReportClient returns a client for the WorkReport from the given config.
func NewWorkReportClient(c config) *WorkReportClient {
	return &WorkReportClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workreport.Hooks(f(g(h())))`.
func (c *WorkReportClient) Use(hooks ...Hook) {
	c.hooks.WorkReport = append(c.hooks.WorkReport, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workreport.Intercept(f(g(h())))`.
func (c *WorkReportClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkReport = append(c.inters.WorkReport, interceptors...)
}

// Create returns a builder for creating a WorkReport entity.
func (c *WorkReportClient) Create() *WorkReportCreate {
	mutation := newWorkReportMutation(c.config, OpCreate)
	return &WorkReportCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkReport entities.
func (c *WorkReportClient) CreateBulk(builders ...*WorkReportCreate) *WorkReportCreateBulk {
	return &WorkReportCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkReportClient) MapCreateBulk(slice any, setFunc func(*WorkReportCreate, int)) *WorkReportCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkReportCreateBulk{err: fmt.Errorf("calling to WorkReportClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkReportCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkReportCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkReport.
func (c *WorkReportClient) Update() *WorkReportUpdate {
	mutation := newWorkReportMutation(c.config, OpUpdate)
	return &WorkReportUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkReportClient) UpdateOne(_m *WorkReport) *WorkReportUpdateOne {
	mutation := newWorkReportMutation(c.config, OpUpdateOne, withWorkReport(_m))
	return &WorkReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkReportClient) UpdateOneID(id string) *WorkReportUpdateOne {
	mutation := newWorkReportMutation(c.config, OpUpdateOne, withWorkReportID(id))
	return &WorkReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkReport.
func (c *WorkReportClient) Delete() *WorkReportDelete {
	mutation := newWorkReportMutation(c.config, OpDelete)
	return &WorkReportDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkReportClient) DeleteOne(_m *WorkReport) *WorkReportDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkReportClient) DeleteOneID(id string) *WorkReportDeleteOne {
	builder := c.Delete().Where(workreport.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkReportDeleteOne{builder}
}

// Query returns a query builder for WorkReport.
func (c *WorkReportClient) Query() *WorkReportQuery {
	return &WorkReportQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkReport},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkReport entity by its id.
func (c *WorkReportClient) Get(ctx context.Context, id string) (*WorkReport, error) {
	return c.Query().Where(workreport.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkReportClient) GetX(ctx context.Context, id string) *WorkReport {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorkReportClient) Hooks() []Hook {
	hooks := c.hooks.WorkReport
	return append(hooks[:len(hooks):len(hooks)], workreport.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *WorkReportClient) Interceptors() []Interceptor {
	inters := c.inters.WorkReport
	return append(inters[:len(inters):len(inters)], workreport.Interceptors[:]...)
}

func (c *WorkReportClient) mutate(ctx context.Context, m *WorkReportMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkReportCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkReportUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkReportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkReportDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkReport mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Condition, DataScope, Department, PolicyRule, Role, User, UserAttribute,
		WorkReport []ent.Hook
	}
	inters struct {
		Condition, DataScope, Department, PolicyRule, Role, User, UserAttribute,
		WorkReport []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
