// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/condition"
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConditionUpdate is the builder for updating Condition entities.
type ConditionUpdate struct {
	config
	hooks     []Hook
	mutation  *ConditionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ConditionUpdate builder.
func (_u *ConditionUpdate) Where(ps ...predicate.Condition) *ConditionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConditionUpdate) SetUpdatedAt(v time.Time) *ConditionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *ConditionUpdate) SetRoleCode(v string) *ConditionUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *ConditionUpdate) SetNillableRoleCode(v *string) *ConditionUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ConditionUpdate) SetOperation(v string) *ConditionUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ConditionUpdate) SetNillableOperation(v *string) *ConditionUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetConditionType sets the "condition_type" field.
func (_u *ConditionUpdate) SetConditionType(v string) *ConditionUpdate {
	_u.mutation.SetConditionType(v)
	return _u
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (_u *ConditionUpdate) SetNillableConditionType(v *string) *ConditionUpdate {
	if v != nil {
		_u.SetConditionType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ConditionUpdate) SetConfig(v string) *ConditionUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ConditionUpdate) SetNillableConfig(v *string) *ConditionUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ConditionUpdate) ClearConfig() *ConditionUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ConditionUpdate) SetGroupID(v string) *ConditionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ConditionUpdate) SetNillableGroupID(v *string) *ConditionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ConditionUpdate) ClearGroupID() *ConditionUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// Mutation returns the ConditionMutation object of the builder.
func (_u *ConditionUpdate) Mutation() *ConditionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConditionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConditionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConditionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConditionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConditionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := condition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConditionUpdate) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := condition.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "Condition.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := condition.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Condition.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConditionType(); ok {
		if err := condition.ConditionTypeValidator(v); err != nil {
			return &ValidationError{Name: "condition_type", err: fmt.Errorf(`ent: validator failed for field "Condition.condition_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := condition.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "Condition.group_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConditionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConditionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConditionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(condition.Table, condition.Columns, sqlgraph.NewFieldSpec(condition.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(condition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(condition.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(condition.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionType(); ok {
		_spec.SetField(condition.FieldConditionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(condition.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(condition.FieldConfig, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(condition.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(condition.FieldGroupID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{condition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConditionUpdateOne is the builder for updating a single Condition entity.
type ConditionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ConditionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConditionUpdateOne) SetUpdatedAt(v time.Time) *ConditionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *ConditionUpdateOne) SetRoleCode(v string) *ConditionUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *ConditionUpdateOne) SetNillableRoleCode(v *string) *ConditionUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ConditionUpdateOne) SetOperation(v string) *ConditionUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ConditionUpdateOne) SetNillableOperation(v *string) *ConditionUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetConditionType sets the "condition_type" field.
func (_u *ConditionUpdateOne) SetConditionType(v string) *ConditionUpdateOne {
	_u.mutation.SetConditionType(v)
	return _u
}

// SetNillableConditionType sets the "condition_type" field if the given value is not nil.
func (_u *ConditionUpdateOne) SetNillableConditionType(v *string) *ConditionUpdateOne {
	if v != nil {
		_u.SetConditionType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ConditionUpdateOne) SetConfig(v string) *ConditionUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ConditionUpdateOne) SetNillableConfig(v *string) *ConditionUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *ConditionUpdateOne) ClearConfig() *ConditionUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ConditionUpdateOne) SetGroupID(v string) *ConditionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ConditionUpdateOne) SetNillableGroupID(v *string) *ConditionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ConditionUpdateOne) ClearGroupID() *ConditionUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// Mutation returns the ConditionMutation object of the builder.
func (_u *ConditionUpdateOne) Mutation() *ConditionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConditionUpdate builder.
func (_u *ConditionUpdateOne) Where(ps ...predicate.Condition) *ConditionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConditionUpdateOne) Select(field string, fields ...string) *ConditionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Condition entity.
func (_u *ConditionUpdateOne) Save(ctx context.Context) (*Condition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConditionUpdateOne) SaveX(ctx context.Context) *Condition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConditionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConditionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConditionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := condition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConditionUpdateOne) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := condition.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "Condition.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := condition.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Condition.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConditionType(); ok {
		if err := condition.ConditionTypeValidator(v); err != nil {
			return &ValidationError{Name: "condition_type", err: fmt.Errorf(`ent: validator failed for field "Condition.condition_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := condition.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "Condition.group_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ConditionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ConditionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ConditionUpdateOne) sqlSave(ctx context.Context) (_node *Condition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(condition.Table, condition.Columns, sqlgraph.NewFieldSpec(condition.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Condition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, condition.FieldID)
		for _, f := range fields {
			if !condition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != condition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(condition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(condition.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(condition.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionType(); ok {
		_spec.SetField(condition.FieldConditionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(condition.FieldConfig, field.TypeString, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(condition.FieldConfig, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(condition.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(condition.FieldGroupID, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Condition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{condition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
