// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cyber-ecosystem/apps/singleton/services/backend/internal/data/ent/datascope"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DataScope is the model entity for the DataScope schema.
type DataScope struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RoleCode holds the value of the "role_code" field.
	RoleCode string `json:"role_code,omitempty"`
	// all, self, dept, custom
	ScopeType string `json:"scope_type,omitempty"`
	// JSON config
	ScopeConfig *string `json:"scope_config,omitempty"`
	// target operation pattern, empty = all
	TargetResource string `json:"target_resource,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DataScope) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case datascope.FieldID, datascope.FieldRoleCode, datascope.FieldScopeType, datascope.FieldScopeConfig, datascope.FieldTargetResource:
			values[i] = new(sql.NullString)
		case datascope.FieldCreatedAt, datascope.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DataScope fields.
func (_m *DataScope) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case datascope.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case datascope.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case datascope.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case datascope.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case datascope.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = value.String
			}
		case datascope.FieldScopeConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_config", values[i])
			} else if value.Valid {
				_m.ScopeConfig = new(string)
				*_m.ScopeConfig = value.String
			}
		case datascope.FieldTargetResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_resource", values[i])
			} else if value.Valid {
				_m.TargetResource = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DataScope.
// This includes values selected through modifiers, order, etc.
func (_m *DataScope) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DataScope.
// Note that you need to call DataScope.Unwrap() before calling this method if this DataScope
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DataScope) Update() *DataScopeUpdateOne {
	return NewDataScopeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DataScope entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DataScope) Unwrap() *DataScope {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DataScope is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DataScope) String() string {
	var builder strings.Builder
	builder.WriteString("DataScope(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(_m.ScopeType)
	builder.WriteString(", ")
	if v := _m.ScopeConfig; v != nil {
		builder.WriteString("scope_config=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("target_resource=")
	builder.WriteString(_m.TargetResource)
	builder.WriteByte(')')
	return builder.String()
}

// DataScopes is a parsable slice of DataScope.
type DataScopes []*DataScope
