// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DrReMain/cyber-ecosystem/kratos/system-service/internal/biz"
	"github.com/DrReMain/cyber-ecosystem/kratos/system-service/internal/conf"
	"github.com/DrReMain/cyber-ecosystem/kratos/system-service/internal/data"
	"github.com/DrReMain/cyber-ecosystem/kratos/system-service/internal/server"
	"github.com/DrReMain/cyber-ecosystem/kratos/system-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRP := data.NewUserRP(dataData, logger)
	userUC := biz.NewUserUC(userRP, logger)
	userService := service.NewUserService(userUC, logger)
	v := server.NewRegistrarList(userService)
	grpcServer := server.NewGRPCServer(confServer, v, logger)
	httpServer := server.NewHTTPServer(confServer, v, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
