// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/biz"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/conf"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/data"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/server"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider, metrics *conf.Metrics, int64Counter metric.Int64Counter, float64Histogram metric.Float64Histogram) (*kratos.App, func(), error) {
	blogServiceClient := data.NewTemplate1BlogService(confData, logger, tracerProvider, int64Counter, float64Histogram)
	dataData, cleanup, err := data.NewData(confData, blogServiceClient)
	if err != nil {
		return nil, nil, err
	}
	readingRP := data.NewReadingRP(dataData)
	readingUC := biz.NewReadingUC(dataData, readingRP)
	readingService := service.NewReadingService(readingUC)
	v := service.NewRegistrarList(readingService)
	grpcServer := server.NewGRPCServer(confServer, logger, v, tracerProvider, int64Counter, float64Histogram)
	httpServer := server.NewHTTPServer(confServer, logger, v, tracerProvider, metrics, int64Counter, float64Histogram)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
