server:
  http:
    addr: 0.0.0.0:11001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:12001
    timeout: 1s
  connect:
    addr: 0.0.0.0:13001
    timeout: 1s
auth:
  secret: secret
log:
  level: debug
  ent:
    enabled: true
    level: debug
    slow_query: true
    slow_query_threshold: 0.2s
  cache:
    enabled: true
    level: debug
    slow_query: true
    slow_query_threshold: 0.2s
  console:
    enabled: true
    color: true
    format: console
  file:
    enabled: false
    path: "./logs/service_2.log"
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true
  loki:
    enabled: true
    url: "http://localhost:3100/loki/api/v1/push"
    labels:
      app: "app_1_service_2"
      env: "development"
    batch_wait: 1s
    batch_size: 1048576 #1MB
data:
  database:
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db_name: cyber_ecosystem_app_1_service_2
    max_open_conns: 100
    max_idle_conns: 50
    conn_max_lifetime: 3600s
    migrate: true
  cache:
    type: redis
    memory:
      otel_enabled: true
    redis:
      addr: localhost:6379
      read_timeout: 0.2s
      write_timeout: 0.2s
      pool_size: 100
      min_idle_conns: 10
      conn_max_lifetime: 3600s
      password: ""
      db: 0
      otel_enabled: true
  grpc_service_1:
    addr: localhost:12000
    timeout: 1s
  connect_service_1:
    addr: localhost:13000
    timeout: 1s
trace:
  endpoint: "localhost:4318"
  insecure: true
ops:
  enabled: true
  addr: "0.0.0.0:14001"
  metrics: "/metrics"
  pprof:
    enabled: true
    cpu_enabled: true
    heap_enabled: true
    goroutine_enabled: true
    mutex_enabled: true
    thread_enabled: true
    trace_enabled: true
