DO $$ BEGIN EXECUTE 'CREATE EXTENSION IF NOT EXISTS vector'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'vector not installed, skipping'; END $$;
DO $$ BEGIN EXECUTE 'CREATE EXTENSION IF NOT EXISTS postgis'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'postgis not installed, skipping'; END $$;
