// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReadingColumns holds the columns for the "reading" table.
	ReadingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 20},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "blog_id", Type: field.TypeString, Comment: "文章ID"},
		{Name: "reading_count", Type: field.TypeInt64, Comment: "阅读量"},
	}
	// ReadingTable holds the schema information for the "reading" table.
	ReadingTable = &schema.Table{
		Name:       "reading",
		Columns:    ReadingColumns,
		PrimaryKey: []*schema.Column{ReadingColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "reading_created_at",
				Unique:  false,
				Columns: []*schema.Column{ReadingColumns[1]},
			},
			{
				Name:    "reading_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ReadingColumns[2]},
			},
			{
				Name:    "reading_blog_id",
				Unique:  true,
				Columns: []*schema.Column{ReadingColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReadingTable,
	}
)

func init() {
	ReadingTable.Annotation = &entsql.Annotation{
		Table: "reading",
	}
}
