server:
  http:
    addr: 0.0.0.0:11000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:12000
    timeout: 1s
  connect:
    addr: 0.0.0.0:13000
    timeout: 1s
log:
  level: debug
  ent:
    enabled: true
    level: debug
    slow_query: true
    slow_query_threshold: 0.2s
  cache:
    enabled: true
    level: debug
    slow_query: true
    slow_query_threshold: 0.2s
  console:
    enabled: true
    color: true
    format: console
  file:
    enabled: false
    path: "./logs/base.log"
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true
  otlp_log:
    enabled: true
    endpoint: "localhost:4318"
    insecure: true
data:
  cache:
    type: redis
    memory:
      otel_enabled: true
    redis:
      addr: localhost:6379
      read_timeout: 0.2s
      write_timeout: 0.2s
      pool_size: 100
      min_idle_conns: 10
      conn_max_lifetime: 3600s
      password: ""
      db: 0
      otel_enabled: true
  database:
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db_name: cyber_ecosystem_genesis_service_base
    max_open_conns: 100
    max_idle_conns: 50
    conn_max_lifetime: 3600s
    migrate: true
  storage:
    max_file_size: 52428800 # 50MB   
    s3:
      endpoint: "http://localhost:19000"
      access_key: "admin@cyber-ecosystem.com"
      secret_key: "Cyber-Ecosystem123"
      bucket: "uploads"
      region: "us-east-1"
trace:
  endpoint: "localhost:4318"
  insecure: true
ops:
  enabled: true
  addr: "0.0.0.0:14000"
  metrics: "/metrics"
  pprof:
    enabled: true
    cpu_enabled: true
    heap_enabled: true
    goroutine_enabled: true
    mutex_enabled: true
    thread_enabled: true
    trace_enabled: true
error_report:
  enabled: true
  dsn: "http://ce217894c77a4ee1babbb76e4e584bf0@localhost:8000/2"
  environment: "development"
  sample_rate: 1.0
