import type { FlowError } from "@cyber-ecosystem/gen-connect-ts/cyber/shared/errors/v1/flow_pb";
import type { GeneralError } from "@cyber-ecosystem/gen-connect-ts/cyber/shared/errors/v1/general_pb";
import type { InfraError } from "@cyber-ecosystem/gen-connect-ts/cyber/shared/errors/v1/infra_pb";
import type { System } from "@cyber-ecosystem/gen-connect-ts/cyber/system/v1/error_reason_pb";
import type { CopyResolver, ErrorKind } from "@cyber-ecosystem/shared-error";
import { m } from "#/paraglide/messages";

export type ConnectReason =
  | `GENERAL_ERROR_${Extract<keyof typeof GeneralError, string>}`
  | `INFRA_ERROR_${Extract<keyof typeof InfraError, string>}`
  | `FLOW_ERROR_${Extract<keyof typeof FlowError, string>}`
  | `SYSTEM_${Extract<keyof typeof System, string>}`;

const REASON_COPY: Record<ConnectReason, () => string> = {
  // General (shared)
  GENERAL_ERROR_UNSPECIFIED: m.error_GENERAL_ERROR_UNSPECIFIED,
  GENERAL_ERROR_INVALID_ARGUMENT: m.error_GENERAL_ERROR_INVALID_ARGUMENT,
  GENERAL_ERROR_VALIDATION_FAILED: m.error_GENERAL_ERROR_VALIDATION_FAILED,
  GENERAL_ERROR_PAGINATION_INVALID_ARGUMENT: m.error_GENERAL_ERROR_PAGINATION_INVALID_ARGUMENT,
  GENERAL_ERROR_UNAUTHENTICATED: m.error_GENERAL_ERROR_UNAUTHENTICATED,
  GENERAL_ERROR_TOKEN_EXPIRED: m.error_GENERAL_ERROR_TOKEN_EXPIRED,
  GENERAL_ERROR_PERMISSION_DENIED: m.error_GENERAL_ERROR_PERMISSION_DENIED,
  GENERAL_ERROR_NOT_FOUND: m.error_GENERAL_ERROR_NOT_FOUND,
  GENERAL_ERROR_METHOD_NOT_ALLOWED: m.error_GENERAL_ERROR_METHOD_NOT_ALLOWED,
  GENERAL_ERROR_ALREADY_EXISTS: m.error_GENERAL_ERROR_ALREADY_EXISTS,
  GENERAL_ERROR_PRECONDITION_FAILED: m.error_GENERAL_ERROR_PRECONDITION_FAILED,
  GENERAL_ERROR_PAYLOAD_TOO_LARGE: m.error_GENERAL_ERROR_PAYLOAD_TOO_LARGE,
  GENERAL_ERROR_RESOURCE_EXHAUSTED: m.error_GENERAL_ERROR_RESOURCE_EXHAUSTED,
  GENERAL_ERROR_INTERNAL: m.error_GENERAL_ERROR_INTERNAL,
  GENERAL_ERROR_NOT_IMPLEMENTED: m.error_GENERAL_ERROR_NOT_IMPLEMENTED,
  GENERAL_ERROR_UNAVAILABLE: m.error_GENERAL_ERROR_UNAVAILABLE,
  GENERAL_ERROR_TIMEOUT: m.error_GENERAL_ERROR_TIMEOUT,
  // Infra (shared)
  INFRA_ERROR_UNSPECIFIED: m.error_INFRA_ERROR_UNSPECIFIED,
  INFRA_ERROR_NETWORK_TIMEOUT: m.error_INFRA_ERROR_NETWORK_TIMEOUT,
  INFRA_ERROR_NETWORK_CONNECTION: m.error_INFRA_ERROR_NETWORK_CONNECTION,
  INFRA_ERROR_NETWORK_DNS: m.error_INFRA_ERROR_NETWORK_DNS,
  INFRA_ERROR_NETWORK_TLS: m.error_INFRA_ERROR_NETWORK_TLS,
  INFRA_ERROR_DB_NOT_FOUND: m.error_INFRA_ERROR_DB_NOT_FOUND,
  INFRA_ERROR_DB_VALIDATION: m.error_INFRA_ERROR_DB_VALIDATION,
  INFRA_ERROR_DB_CONSTRAINT: m.error_INFRA_ERROR_DB_CONSTRAINT,
  INFRA_ERROR_DB_NOT_SINGULAR: m.error_INFRA_ERROR_DB_NOT_SINGULAR,
  INFRA_ERROR_DB_NOT_LOADED: m.error_INFRA_ERROR_DB_NOT_LOADED,
  INFRA_ERROR_DB_INTERNAL: m.error_INFRA_ERROR_DB_INTERNAL,
  INFRA_ERROR_DB_DEADLOCK: m.error_INFRA_ERROR_DB_DEADLOCK,
  INFRA_ERROR_DB_CONNECTION: m.error_INFRA_ERROR_DB_CONNECTION,
  INFRA_ERROR_CACHE_MISS: m.error_INFRA_ERROR_CACHE_MISS,
  INFRA_ERROR_CACHE_KEY_NOT_FOUND: m.error_INFRA_ERROR_CACHE_KEY_NOT_FOUND,
  INFRA_ERROR_CACHE_SESSION_NOT_FOUND: m.error_INFRA_ERROR_CACHE_SESSION_NOT_FOUND,
  INFRA_ERROR_CACHE_QUOTA_EXCEEDED: m.error_INFRA_ERROR_CACHE_QUOTA_EXCEEDED,
  INFRA_ERROR_CACHE_INVALID_ARGUMENT: m.error_INFRA_ERROR_CACHE_INVALID_ARGUMENT,
  INFRA_ERROR_CACHE_UNAVAILABLE: m.error_INFRA_ERROR_CACHE_UNAVAILABLE,
  INFRA_ERROR_CACHE_LOCK_NOT_ACQUIRED: m.error_INFRA_ERROR_CACHE_LOCK_NOT_ACQUIRED,
  INFRA_ERROR_STORAGE_NOT_FOUND: m.error_INFRA_ERROR_STORAGE_NOT_FOUND,
  INFRA_ERROR_STORAGE_FORBIDDEN: m.error_INFRA_ERROR_STORAGE_FORBIDDEN,
  INFRA_ERROR_STORAGE_SIZE_EXCEED: m.error_INFRA_ERROR_STORAGE_SIZE_EXCEED,
  INFRA_ERROR_STORAGE_UNAVAILABLE: m.error_INFRA_ERROR_STORAGE_UNAVAILABLE,
  INFRA_ERROR_STORAGE_INVALID_ARGUMENT: m.error_INFRA_ERROR_STORAGE_INVALID_ARGUMENT,
  INFRA_ERROR_MQ_INVALID_ARGUMENT: m.error_INFRA_ERROR_MQ_INVALID_ARGUMENT,
  INFRA_ERROR_MQ_UNAVAILABLE: m.error_INFRA_ERROR_MQ_UNAVAILABLE,
  INFRA_ERROR_MQ_TIMEOUT: m.error_INFRA_ERROR_MQ_TIMEOUT,
  // Flow (shared)
  FLOW_ERROR_UNSPECIFIED: m.error_FLOW_ERROR_UNSPECIFIED,
  FLOW_ERROR_RATE_LIMITED: m.error_FLOW_ERROR_RATE_LIMITED,
  FLOW_ERROR_CIRCUIT_BREAKER: m.error_FLOW_ERROR_CIRCUIT_BREAKER,
  FLOW_ERROR_QUOTA_EXCEEDED: m.error_FLOW_ERROR_QUOTA_EXCEEDED,
  FLOW_ERROR_CONCURRENT_LIMIT: m.error_FLOW_ERROR_CONCURRENT_LIMIT,
  // System (service business)
  SYSTEM_UNSPECIFIED: m.error_SYSTEM_UNSPECIFIED,
  SYSTEM_LOGIN_FAILED: m.error_SYSTEM_LOGIN_FAILED,
  SYSTEM_DEPT_SELF_PARENT: m.error_SYSTEM_DEPT_SELF_PARENT,
  SYSTEM_DEPT_CYCLE: m.error_SYSTEM_DEPT_CYCLE,
  SYSTEM_DEPT_HAS_CHILDREN: m.error_SYSTEM_DEPT_HAS_CHILDREN,
  SYSTEM_DEPT_NOT_FOUND: m.error_SYSTEM_DEPT_NOT_FOUND,
  SYSTEM_DEPT_HAS_USERS: m.error_SYSTEM_DEPT_HAS_USERS,
  SYSTEM_DEPT_MEMBER_NOT_FOUND: m.error_SYSTEM_DEPT_MEMBER_NOT_FOUND,
  SYSTEM_ROLE_NOT_FOUND: m.error_SYSTEM_ROLE_NOT_FOUND,
  SYSTEM_ROLE_HAS_BINDINGS: m.error_SYSTEM_ROLE_HAS_BINDINGS,
  SYSTEM_USER_SELF_DELETE: m.error_SYSTEM_USER_SELF_DELETE,
  SYSTEM_USER_SELF_DISABLE: m.error_SYSTEM_USER_SELF_DISABLE,
  SYSTEM_USER_DISABLED: m.error_SYSTEM_USER_DISABLED,
  SYSTEM_PERMISSION_INVALID_OPERATION: m.error_SYSTEM_PERMISSION_INVALID_OPERATION,
  SYSTEM_POLICY_UNKNOWN_KIND: m.error_SYSTEM_POLICY_UNKNOWN_KIND,
  SYSTEM_POLICY_INVALID_PARAMS: m.error_SYSTEM_POLICY_INVALID_PARAMS,
  SYSTEM_POLICY_NOT_FOUND: m.error_SYSTEM_POLICY_NOT_FOUND,
  SYSTEM_AUTHZ_POLICY_DENIED: m.error_SYSTEM_AUTHZ_POLICY_DENIED,
  SYSTEM_FILE_NOT_FOUND: m.error_SYSTEM_FILE_NOT_FOUND,
  SYSTEM_FILE_TOO_LARGE: m.error_SYSTEM_FILE_TOO_LARGE,
  SYSTEM_FILE_INVALID_STATE: m.error_SYSTEM_FILE_INVALID_STATE,
};

const TITLES: Record<ErrorKind, () => string> = {
  unknown: m.error_client_title,
  network: m.error_network_title,
  server: m.error_server_title,
  canceled: m.error_cancel_title,
  business: m.error_business_title,
  auth: m.error_auth_title,
  forbidden: m.error_forbidden_title,
};

export const copy: CopyResolver = {
  title: (kind) => TITLES[kind](),
  message: (envelope) => {
    if (envelope.reason !== undefined) {
      return REASON_COPY[envelope.reason as ConnectReason]?.() ?? envelope.message;
    }
    if (envelope.kind === "unknown" || envelope.kind === "network") return "";
    return envelope.message;
  },
};
