package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "Usage: %s <proto_file> <output_dir> [-locale=en-US,zh-CN]\n", os.Args[0])
		os.Exit(1)
	}

	protoPath := ""
	outputDir := ""
	var locales string

	for i := 1; i < len(os.Args); i++ {
		arg := os.Args[i]
		if strings.HasPrefix(arg, "-locale=") {
			locales = strings.TrimPrefix(arg, "-locale=")
		} else if protoPath == "" {
			protoPath = arg
		} else if outputDir == "" {
			outputDir = arg
		}
	}

	if locales == "" {
		fmt.Fprintf(os.Stderr, "Error: -locale flag is required\n")
		os.Exit(1)
	}

	if protoPath == "" || outputDir == "" {
		fmt.Fprintf(os.Stderr, "Usage: %s <proto_file> <output_dir> [-locale=en-US,zh-CN]\n", os.Args[0])
		os.Exit(1)
	}

	localeList := strings.Split(locales, ",")
	if len(localeList) == 0 {
		fmt.Fprintf(os.Stderr, "Error: at least one locale must be specified\n")
		os.Exit(1)
	}

	data, err := os.ReadFile(protoPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read proto file: %v\n", err)
		os.Exit(1)
	}

	enumValues := parseErrorReasonEnum(string(data))
	if len(enumValues) == 0 {
		fmt.Fprintf(os.Stderr, "No enum values found in %s\n", protoPath)
		os.Exit(1)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	serviceName := guessServiceName(protoPath)

	for _, locale := range localeList {
		locale = strings.TrimSpace(locale)
		langPath := filepath.Join(outputDir, serviceName+"."+locale+".yaml")
		generateTranslationFile(langPath, enumValues, locale)
	}

	fmt.Printf("Generated translation files in %s: %v\n", outputDir, localeList)
}

func parseErrorReasonEnum(content string) []string {
	var values []string

	enumRegex := regexp.MustCompile(`enum\s+ErrorReason\s*\{([^}]+)\}`)
	matches := enumRegex.FindStringSubmatch(content)
	if len(matches) < 2 {
		return values
	}

	enumBody := matches[1]

	valueRegex := regexp.MustCompile(`ERROR_REASON_\w+\s*=\s*\d+`)
	valueMatches := valueRegex.FindAllString(enumBody, -1)

	for _, v := range valueMatches {
		nameRegex := regexp.MustCompile(`(ERROR_REASON_\w+)`)
		nameMatch := nameRegex.FindStringSubmatch(v)
		if len(nameMatch) > 1 {
			values = append(values, nameMatch[1])
		}
	}

	return values
}

func guessServiceName(protoPath string) string {
	dir := filepath.Dir(protoPath)
	parts := strings.Split(dir, string(filepath.Separator))
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "app"
}

func generateTranslationFile(outputPath string, values []string, locale string) {
	existing := make(map[string]string)

	if _, err := os.Stat(outputPath); err == nil {
		data, err := os.ReadFile(outputPath)
		if err == nil {
			existing = parseYamlFile(data)
		}
	}

	newFile := make(map[string]string)
	for _, v := range values {
		if val, ok := existing[v]; ok && val != "" {
			newFile[v] = val
		} else {
			newFile[v] = ""
		}
	}

	orphans := []string{}
	for key := range existing {
		if _, exists := newFile[key]; !exists {
			orphans = append(orphans, key)
		}
	}

	header := fmt.Sprintf(`# Generated by geni18n. DO NOT EDIT.
# Service: %s
# Locale: %s
#
# =================================================================
# go-i18n supported fields for each message ID:
#   - Other: CLDR plural form "other" (REQUIRED - default/fallback)
#   - One:   CLDR plural form "one" (e.g., 1 in English, 0-1 in French)
#   - Zero:  CLDR plural form "zero" (Language dependent; e.g., English 0 uses "other")
#   - Two:   CLDR plural form "two" (e.g., Dual form in Arabic)
#   - Few:   CLDR plural form "few" (e.g., 2-4 in Russian)
#   - Many:  CLDR plural form "many" (e.g., 11-99 in Polish)
#   - Description: Context for translators
#
# Note: Not all languages support all plural forms. 
# Refer to CLDR rules for specific language requirements.
# =================================================================
#
# Format 1 - Message with variables (Standard):
#   GREETING: "Hello {{.Name}}, welcome to {{.City}}"
#
# Format 2 - Plural message (use "Count" or "count" in metadata):
#   ERROR_COUNT:
#     one: "You have {{.Count}} error"
#     other: "You have {{.Count}} errors"
#
# Format 3 - Message with description:
#   LOGIN_BUTTON:
#     other: "Sign In"
#     description: "Text on the primary login button"
#
# Format 4 - Conditional template (bool/int/float auto-converted from string):
#   STATUS: "Status: {{if .Active}}Online{{else}}Offline{{end}}"
#   PRICE: "Price: {{if gt .Price 100}}expensive{{else}}affordable{{end}}"
# =================================================================

`, guessServiceName(outputPath), locale)

	f, err := os.Create(outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create file %s: %v\n", outputPath, err)
		return
	}
	defer f.Close()

	if _, err := f.WriteString(header); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write header to %s: %v\n", outputPath, err)
		return
	}

	for _, v := range values {
		fmt.Fprintf(f, "%s: %q\n", v, newFile[v])
	}

	if len(orphans) > 0 {
		fmt.Printf("Removed orphan keys from %s: %v\n", outputPath, orphans)
	}
}

func parseYamlFile(data []byte) map[string]string {
	result := make(map[string]string)
	lines := strings.Split(string(data), "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		value = strings.Trim(value, "\"")

		if key != "" && !strings.Contains(key, ".") {
			result[key] = value
		}
	}

	return result
}
