package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	var protoPaths []string
	outputDir := ""
	var locales string
	var protosFile string
	var nameOverride string

	for i := 1; i < len(os.Args); i++ {
		arg := os.Args[i]
		if strings.HasPrefix(arg, "-locale=") {
			locales = strings.TrimPrefix(arg, "-locale=")
		} else if strings.HasPrefix(arg, "-protos=") {
			protosFile = strings.TrimPrefix(arg, "-protos=")
		} else if strings.HasPrefix(arg, "-name=") {
			nameOverride = strings.TrimPrefix(arg, "-name=")
		}
	}

	// Collect positional args (non-flag)
	var nonFlagArgs []string
	for i := 1; i < len(os.Args); i++ {
		arg := os.Args[i]
		if !strings.HasPrefix(arg, "-") {
			nonFlagArgs = append(nonFlagArgs, arg)
		}
	}

	// Proto files from -protos file or positional args
	if protosFile != "" {
		paths, err := readProtoList(protosFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to read proto list: %v\n", err)
			os.Exit(1)
		}
		protoPaths = paths
		if len(nonFlagArgs) < 1 {
			fmt.Fprintf(os.Stderr, "Usage: %s -protos=<file> <output_dir> [-locale=en-US,zh-CN]\n", os.Args[0])
			os.Exit(1)
		}
		outputDir = nonFlagArgs[0]
	} else {
		if len(nonFlagArgs) < 2 {
			fmt.Fprintf(os.Stderr, "Usage: %s <proto_file>... <output_dir> [-locale=en-US,zh-CN]\n       %s -protos=<file> <output_dir> [-locale=en-US,zh-CN]\n", os.Args[0], os.Args[0])
			os.Exit(1)
		}
		protoPaths = nonFlagArgs[:len(nonFlagArgs)-1]
		outputDir = nonFlagArgs[len(nonFlagArgs)-1]
	}

	if locales == "" {
		fmt.Fprintf(os.Stderr, "Error: -locale flag is required\n")
		os.Exit(1)
	}

	localeList := strings.Split(locales, ",")
	if len(localeList) == 0 {
		fmt.Fprintf(os.Stderr, "Error: at least one locale must be specified\n")
		os.Exit(1)
	}

	var allValues []string
	for _, protoPath := range protoPaths {
		data, err := os.ReadFile(protoPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to read proto file %s: %v\n", protoPath, err)
			os.Exit(1)
		}

		values := parseAllEnums(string(data))
		if len(values) == 0 {
			fmt.Printf("No enum values found in %s, skipping\n", protoPath)
			continue
		}
		allValues = append(allValues, values...)
	}

	if len(allValues) == 0 {
		fmt.Fprintf(os.Stderr, "No enum values found in any proto file\n")
		os.Exit(1)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	serviceName := nameOverride
	if serviceName == "" {
		serviceName = guessServiceName(protoPaths[0])
	}

	for _, locale := range localeList {
		locale = strings.TrimSpace(locale)
		langPath := filepath.Join(outputDir, serviceName+"."+locale+".yaml")
		generateTranslationFile(langPath, allValues, locale)
	}

	fmt.Printf("Generated translation files in %s: %v (%d keys)\n", outputDir, localeList, len(allValues))
}

// readProtoList reads a text file with one proto path per line.
// Empty lines and lines starting with # are skipped.
func readProtoList(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var paths []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		paths = append(paths, line)
	}
	return paths, scanner.Err()
}

// parseAllEnums extracts all enum value names from all enums in a proto file.
func parseAllEnums(content string) []string {
	var values []string

	enumRegex := regexp.MustCompile(`(?s)enum\s+\w+\s*\{(.*?)\}`)
	enumMatches := enumRegex.FindAllStringSubmatch(content, -1)

	valueRegex := regexp.MustCompile(`([A-Z][A-Z0-9_]*)\s*=\s*\d+`)

	for _, match := range enumMatches {
		if len(match) < 2 {
			continue
		}
		enumBody := match[1]

		valueMatches := valueRegex.FindAllStringSubmatch(enumBody, -1)
		for _, vm := range valueMatches {
			name := vm[1]
			if strings.HasPrefix(name, "OPTION") {
				continue
			}
			values = append(values, name)
		}
	}

	return values
}

func guessServiceName(protoPath string) string {
	dir := filepath.Dir(protoPath)
	parts := strings.Split(dir, string(filepath.Separator))
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "app"
}

func generateTranslationFile(outputPath string, values []string, locale string) {
	existing := make(map[string]string)

	if _, err := os.Stat(outputPath); err == nil {
		data, err := os.ReadFile(outputPath)
		if err == nil {
			existing = parseYamlFile(data)
		}
	}

	newFile := make(map[string]string)
	for _, v := range values {
		if val, ok := existing[v]; ok && val != "" {
			newFile[v] = val
		} else {
			newFile[v] = ""
		}
	}

	orphans := []string{}
	for key := range existing {
		if _, exists := newFile[key]; !exists {
			orphans = append(orphans, key)
		}
	}

	header := fmt.Sprintf(`# Generated by geni18n. DO NOT EDIT.
# Service: %s
# Locale: %s
#
# =================================================================
# go-i18n supported fields for each message ID:
#   - Other: CLDR plural form "other" (REQUIRED - default/fallback)
#   - One:   CLDR plural form "one" (e.g., 1 in English, 0-1 in French)
#   - Zero:  CLDR plural form "zero" (Language dependent; e.g., English 0 uses "other")
#   - Two:   CLDR plural form "two" (e.g., Dual form in Arabic)
#   - Few:   CLDR plural form "few" (e.g., 2-4 in Russian)
#   - Many:  CLDR plural form "many" (e.g., 11-99 in Polish)
#   - Description: Context for translators
#
# Note: Not all languages support all plural forms.
# Refer to CLDR rules for specific language requirements.
# =================================================================
#
# Format 1 - Message with variables (Standard):
#   GREETING: "Hello {{.Name}}, welcome to {{.City}}"
#
# Format 2 - Plural message (use "Count" or "count" in metadata):
#   ERROR_COUNT:
#     one: "You have {{.Count}} error"
#     other: "You have {{.Count}} errors"
#
# Format 3 - Message with description:
#   LOGIN_BUTTON:
#     other: "Sign In"
#     description: "Text on the primary login button"
#
# Format 4 - Conditional template (bool/int/float auto-converted from string):
#   STATUS: "Status: {{if .Active}}Online{{else}}Offline{{end}}"
#   PRICE: "Price: {{if gt .Price 100}}expensive{{else}}affordable{{end}}"
# =================================================================

`, guessServiceName(outputPath), locale)

	f, err := os.Create(outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create file %s: %v\n", outputPath, err)
		return
	}
	defer f.Close()

	if _, err := f.WriteString(header); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write header to %s: %v\n", outputPath, err)
		return
	}

	for _, v := range values {
		fmt.Fprintf(f, "%s: %q\n", v, newFile[v])
	}

	if len(orphans) > 0 {
		fmt.Printf("Removed orphan keys from %s: %v\n", outputPath, orphans)
	}
}

func parseYamlFile(data []byte) map[string]string {
	result := make(map[string]string)
	lines := strings.Split(string(data), "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		value = strings.Trim(value, "\"")

		if key != "" && !strings.Contains(key, ".") {
			result[key] = value
		}
	}

	return result
}
