// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file errors/codes_auth.proto (package errors, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_errors_errors } from "./errors_pb";

/**
 * Describes the file errors/codes_auth.proto.
 */
export const file_errors_codes_auth: GenFile = /*@__PURE__*/
  fileDesc("ChdlcnJvcnMvY29kZXNfYXV0aC5wcm90bxIGZXJyb3JzKokDCglBdXRoRXJyb3ISIAoWQVVUSF9FUlJPUl9VTlNQRUNJRklFRBAAGgSoRfQDEiMKGEFVVEhfRVJST1JfVE9LRU5fRVhQSVJFRBCIJxoEqEWRAxIjChhBVVRIX0VSUk9SX1RPS0VOX0lOVkFMSUQQiScaBKhFkQMSIwoYQVVUSF9FUlJPUl9UT0tFTl9NSVNTSU5HEIonGgSoRZEDEiMKGEFVVEhfRVJST1JfVE9LRU5fUkVWT0tFRBCLJxoEqEWRAxInChxBVVRIX0VSUk9SX1BFUk1JU1NJT05fREVOSUVEEIwnGgSoRZMDEiYKG0FVVEhfRVJST1JfQUNDT1VOVF9ESVNBQkxFRBCNJxoEqEWTAxIkChlBVVRIX0VSUk9SX0FDQ09VTlRfTE9DS0VEEI4nGgSoRZMDEiIKF0FVVEhfRVJST1JfTUZBX1JFUVVJUkVEEI8nGgSoRZMDEiUKGkFVVEhfRVJST1JfU0VTU0lPTl9FWFBJUkVEEJAnGgSoRZEDGgSgRZEDQixaKmN5YmVyLWVjb3N5c3RlbS9jb250cmFjdHMvZ28vZXJyb3JzO2Vycm9yc2IGcHJvdG8z", [file_errors_errors]);

/**
 * Authentication & authorization errors: token, session, MFA, account status (5xxx).
 *
 * @generated from enum errors.AuthError
 */
export enum AuthError {
  /**
   * @generated from enum value: AUTH_ERROR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Token has expired
   *
   * @generated from enum value: AUTH_ERROR_TOKEN_EXPIRED = 5000;
   */
  TOKEN_EXPIRED = 5000,

  /**
   * Token is invalid
   *
   * @generated from enum value: AUTH_ERROR_TOKEN_INVALID = 5001;
   */
  TOKEN_INVALID = 5001,

  /**
   * Token not provided
   *
   * @generated from enum value: AUTH_ERROR_TOKEN_MISSING = 5002;
   */
  TOKEN_MISSING = 5002,

  /**
   * Token has been revoked
   *
   * @generated from enum value: AUTH_ERROR_TOKEN_REVOKED = 5003;
   */
  TOKEN_REVOKED = 5003,

  /**
   * Insufficient permissions
   *
   * @generated from enum value: AUTH_ERROR_PERMISSION_DENIED = 5004;
   */
  PERMISSION_DENIED = 5004,

  /**
   * Account is disabled
   *
   * @generated from enum value: AUTH_ERROR_ACCOUNT_DISABLED = 5005;
   */
  ACCOUNT_DISABLED = 5005,

  /**
   * Account is locked
   *
   * @generated from enum value: AUTH_ERROR_ACCOUNT_LOCKED = 5006;
   */
  ACCOUNT_LOCKED = 5006,

  /**
   * Multi-factor authentication required
   *
   * @generated from enum value: AUTH_ERROR_MFA_REQUIRED = 5007;
   */
  MFA_REQUIRED = 5007,

  /**
   * Session has expired
   *
   * @generated from enum value: AUTH_ERROR_SESSION_EXPIRED = 5008;
   */
  SESSION_EXPIRED = 5008,
}

/**
 * Describes the enum errors.AuthError.
 */
export const AuthErrorSchema: GenEnum<AuthError> = /*@__PURE__*/
  enumDesc(file_errors_codes_auth, 0);

