/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPlaygroundHttpRouteImport } from './routes/_app.playground.http'
import { Route as AppPlaygroundFileRouteImport } from './routes/_app.playground.file'
import { Route as AppPlaygroundConnectRouteImport } from './routes/_app.playground.connect'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundHttpRoute = AppPlaygroundHttpRouteImport.update({
  id: '/playground/http',
  path: '/playground/http',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundFileRoute = AppPlaygroundFileRouteImport.update({
  id: '/playground/file',
  path: '/playground/file',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundConnectRoute = AppPlaygroundConnectRouteImport.update({
  id: '/playground/connect',
  path: '/playground/connect',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/playground/connect': typeof AppPlaygroundConnectRoute
  '/playground/file': typeof AppPlaygroundFileRoute
  '/playground/http': typeof AppPlaygroundHttpRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/playground/connect': typeof AppPlaygroundConnectRoute
  '/playground/file': typeof AppPlaygroundFileRoute
  '/playground/http': typeof AppPlaygroundHttpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/playground/connect': typeof AppPlaygroundConnectRoute
  '/_app/playground/file': typeof AppPlaygroundFileRoute
  '/_app/playground/http': typeof AppPlaygroundHttpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground/connect'
    | '/playground/file'
    | '/playground/http'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playground/connect' | '/playground/file' | '/playground/http'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/playground/connect'
    | '/_app/playground/file'
    | '/_app/playground/http'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/http': {
      id: '/_app/playground/http'
      path: '/playground/http'
      fullPath: '/playground/http'
      preLoaderRoute: typeof AppPlaygroundHttpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/file': {
      id: '/_app/playground/file'
      path: '/playground/file'
      fullPath: '/playground/file'
      preLoaderRoute: typeof AppPlaygroundFileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/connect': {
      id: '/_app/playground/connect'
      path: '/playground/connect'
      fullPath: '/playground/connect'
      preLoaderRoute: typeof AppPlaygroundConnectRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPlaygroundConnectRoute: typeof AppPlaygroundConnectRoute
  AppPlaygroundFileRoute: typeof AppPlaygroundFileRoute
  AppPlaygroundHttpRoute: typeof AppPlaygroundHttpRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPlaygroundConnectRoute: AppPlaygroundConnectRoute,
  AppPlaygroundFileRoute: AppPlaygroundFileRoute,
  AppPlaygroundHttpRoute: AppPlaygroundHttpRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
