// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file genesis/api/v1/messages/resource.proto (package api.genesis.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file genesis/api/v1/messages/resource.proto.
 */
export const file_genesis_api_v1_messages_resource: GenFile = /*@__PURE__*/
  fileDesc("CiZnZW5lc2lzL2FwaS92MS9tZXNzYWdlcy9yZXNvdXJjZS5wcm90bxIOYXBpLmdlbmVzaXMudjEixgEKBk1ldGhvZBIMCgRuYW1lGAEgASgJEhEKCWZ1bGxfbmFtZRgCIAEoCRIUCgxyZXF1ZXN0X25hbWUYAyABKAkSGQoRcmVxdWVzdF9mdWxsX25hbWUYBCABKAkSFQoNcmVzcG9uc2VfbmFtZRgFIAEoCRIaChJyZXNwb25zZV9mdWxsX25hbWUYBiABKAkSEwoLaHR0cF9tZXRob2QYByABKAkSEQoJaHR0cF9wYXRoGAggASgJEg8KB2NvbW1lbnQYCSABKAkiigEKB1NlcnZpY2USDAoEbmFtZRgBIAEoCRIRCglmdWxsX25hbWUYAiABKAkSDwoHcGFja2FnZRgDIAEoCRITCgtzb3VyY2VfZmlsZRgEIAEoCRIPCgdjb21tZW50GAUgASgJEicKB21ldGhvZHMYBiADKAsyFi5hcGkuZ2VuZXNpcy52MS5NZXRob2QiFQoTTGlzdFJlc291cmNlUmVxdWVzdCI9ChRMaXN0UmVzb3VyY2VSZXNwb25zZRIlCgRsaXN0GAEgAygLMhcuYXBpLmdlbmVzaXMudjEuU2VydmljZUIyWjBjeWJlci1lY29zeXN0ZW0vYXBwcy9nZW5lc2lzL2dlbi9nby92MTtnZW5lc2lzVjFiBnByb3RvMw");

/**
 * @generated from message api.genesis.v1.Method
 */
export type Method = Message<"api.genesis.v1.Method"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string full_name = 2;
   */
  fullName: string;

  /**
   * @generated from field: string request_name = 3;
   */
  requestName: string;

  /**
   * @generated from field: string request_full_name = 4;
   */
  requestFullName: string;

  /**
   * @generated from field: string response_name = 5;
   */
  responseName: string;

  /**
   * @generated from field: string response_full_name = 6;
   */
  responseFullName: string;

  /**
   * @generated from field: string http_method = 7;
   */
  httpMethod: string;

  /**
   * @generated from field: string http_path = 8;
   */
  httpPath: string;

  /**
   * @generated from field: string comment = 9;
   */
  comment: string;
};

/**
 * Describes the message api.genesis.v1.Method.
 * Use `create(MethodSchema)` to create a new message.
 */
export const MethodSchema: GenMessage<Method> = /*@__PURE__*/
  messageDesc(file_genesis_api_v1_messages_resource, 0);

/**
 * @generated from message api.genesis.v1.Service
 */
export type Service = Message<"api.genesis.v1.Service"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string full_name = 2;
   */
  fullName: string;

  /**
   * @generated from field: string package = 3;
   */
  package: string;

  /**
   * @generated from field: string source_file = 4;
   */
  sourceFile: string;

  /**
   * @generated from field: string comment = 5;
   */
  comment: string;

  /**
   * @generated from field: repeated api.genesis.v1.Method methods = 6;
   */
  methods: Method[];
};

/**
 * Describes the message api.genesis.v1.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export const ServiceSchema: GenMessage<Service> = /*@__PURE__*/
  messageDesc(file_genesis_api_v1_messages_resource, 1);

/**
 * @generated from message api.genesis.v1.ListResourceRequest
 */
export type ListResourceRequest = Message<"api.genesis.v1.ListResourceRequest"> & {
};

/**
 * Describes the message api.genesis.v1.ListResourceRequest.
 * Use `create(ListResourceRequestSchema)` to create a new message.
 */
export const ListResourceRequestSchema: GenMessage<ListResourceRequest> = /*@__PURE__*/
  messageDesc(file_genesis_api_v1_messages_resource, 2);

/**
 * @generated from message api.genesis.v1.ListResourceResponse
 */
export type ListResourceResponse = Message<"api.genesis.v1.ListResourceResponse"> & {
  /**
   * @generated from field: repeated api.genesis.v1.Service list = 1;
   */
  list: Service[];
};

/**
 * Describes the message api.genesis.v1.ListResourceResponse.
 * Use `create(ListResourceResponseSchema)` to create a new message.
 */
export const ListResourceResponseSchema: GenMessage<ListResourceResponse> = /*@__PURE__*/
  messageDesc(file_genesis_api_v1_messages_resource, 3);

