server:
  http:
    addr: 0.0.0.0:11001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:12001
    timeout: 1s
log:
  level: debug
  ent:
    enabled: true
    level: debug
    slow_query: true
    slow_query_threshold: 0.2s
  console:
    enabled: true
    color: true
    format: console
  file:
    enabled: false
    path: "../../logs/examples-template2/app.log"
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true
  loki:
    enabled: true
    url: "http://localhost:3100/loki/api/v1/push"
    labels:
      app: "examples-template2"
      env: "development"
    batch_wait: 1s
    batch_size: 1048576 #1MB
data:
  database:
    driver: postgres
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    db_name: cyber_ecosystem_template2
    max_open_conns: 100
    max_idle_conns: 100
    conn_max_lifetime: 3600s
    migrate: false
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  service_template1:
    addr: 127.0.0.1:12000
    timeout: 1s
trace:
  endpoint: "http://127.0.0.1:14268/api/traces"
metrics:
  path: "/metrics"
