server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  database:
    driver: postgres
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    db_name: cyber_ecosystem_template2
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 3600s
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  service_template1:
    addr: 127.0.0.1:9001
    timeout: 1s
trace:
  endpoint: "http://127.0.0.1:14268/api/traces"
