server:
  http: {addr: 0.0.0.0:11002, timeout: 1s}
  grpc: {addr: 0.0.0.0:12002, timeout: 1s}
  connect: {addr: 0.0.0.0:13002, timeout: 1s}
remote:
  system: localhost:12001
  system_connect: localhost:13001
observability:
  endpoint: otlp.cyber.test:80
  insecure: true
  trace:
    enabled: false
  metrics:
    enabled: false
  log:
    level: debug
    console: true
    otlp: false
#    file:
#      path: app.log
#      max_size_mb: 100 # MiB (单文件最大)
#      max_backups: 10 # 个 (保留备份数)
#      max_age_days: 30 # 天 (最大保留天数)
#      compress: true
