// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file genesis/api/v1/bff_admin/admin_article.proto (package api.genesis.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { AdminArticleService } from "./admin_article_pb";

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.CreateArticle
 */
export const createArticle = AdminArticleService.method.createArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.UpdateArticle
 */
export const updateArticle = AdminArticleService.method.updateArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.DeleteArticle
 */
export const deleteArticle = AdminArticleService.method.deleteArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.GetArticle
 */
export const getArticle = AdminArticleService.method.getArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.QueryArticle
 */
export const queryArticle = AdminArticleService.method.queryArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.SortArticle
 */
export const sortArticle = AdminArticleService.method.sortArticle;

/**
 * @generated from rpc api.genesis.v1.AdminArticleService.UpdateArticleStatus
 */
export const updateArticleStatus = AdminArticleService.method.updateArticleStatus;
