// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/data/ent/predicate"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/data/ent/reading"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeReading = "Reading"
)

// ReadingMutation represents an operation that mutates the Reading nodes in the graph.
type ReadingMutation struct {
	config
	op               Op
	typ              string
	id               *string
	created_at       *time.Time
	updated_at       *time.Time
	blog_id          *string
	reading_count    *int64
	addreading_count *int64
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*Reading, error)
	predicates       []predicate.Reading
}

var _ ent.Mutation = (*ReadingMutation)(nil)

// readingOption allows management of the mutation configuration using functional options.
type readingOption func(*ReadingMutation)

// newReadingMutation creates new mutation for the Reading entity.
func newReadingMutation(c config, op Op, opts ...readingOption) *ReadingMutation {
	m := &ReadingMutation{
		config:        c,
		op:            op,
		typ:           TypeReading,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withReadingID sets the ID field of the mutation.
func withReadingID(id string) readingOption {
	return func(m *ReadingMutation) {
		var (
			err   error
			once  sync.Once
			value *Reading
		)
		m.oldValue = func(ctx context.Context) (*Reading, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Reading.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withReading sets the old Reading of the mutation.
func withReading(node *Reading) readingOption {
	return func(m *ReadingMutation) {
		m.oldValue = func(context.Context) (*Reading, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ReadingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ReadingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Reading entities.
func (m *ReadingMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ReadingMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ReadingMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Reading.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *ReadingMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ReadingMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Reading entity.
// If the Reading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ReadingMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ReadingMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ReadingMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Reading entity.
// If the Reading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ReadingMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetBlogID sets the "blog_id" field.
func (m *ReadingMutation) SetBlogID(s string) {
	m.blog_id = &s
}

// BlogID returns the value of the "blog_id" field in the mutation.
func (m *ReadingMutation) BlogID() (r string, exists bool) {
	v := m.blog_id
	if v == nil {
		return
	}
	return *v, true
}

// OldBlogID returns the old "blog_id" field's value of the Reading entity.
// If the Reading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingMutation) OldBlogID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBlogID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBlogID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBlogID: %w", err)
	}
	return oldValue.BlogID, nil
}

// ResetBlogID resets all changes to the "blog_id" field.
func (m *ReadingMutation) ResetBlogID() {
	m.blog_id = nil
}

// SetReadingCount sets the "reading_count" field.
func (m *ReadingMutation) SetReadingCount(i int64) {
	m.reading_count = &i
	m.addreading_count = nil
}

// ReadingCount returns the value of the "reading_count" field in the mutation.
func (m *ReadingMutation) ReadingCount() (r int64, exists bool) {
	v := m.reading_count
	if v == nil {
		return
	}
	return *v, true
}

// OldReadingCount returns the old "reading_count" field's value of the Reading entity.
// If the Reading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingMutation) OldReadingCount(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldReadingCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldReadingCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldReadingCount: %w", err)
	}
	return oldValue.ReadingCount, nil
}

// AddReadingCount adds i to the "reading_count" field.
func (m *ReadingMutation) AddReadingCount(i int64) {
	if m.addreading_count != nil {
		*m.addreading_count += i
	} else {
		m.addreading_count = &i
	}
}

// AddedReadingCount returns the value that was added to the "reading_count" field in this mutation.
func (m *ReadingMutation) AddedReadingCount() (r int64, exists bool) {
	v := m.addreading_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetReadingCount resets all changes to the "reading_count" field.
func (m *ReadingMutation) ResetReadingCount() {
	m.reading_count = nil
	m.addreading_count = nil
}

// Where appends a list predicates to the ReadingMutation builder.
func (m *ReadingMutation) Where(ps ...predicate.Reading) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ReadingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ReadingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Reading, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ReadingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ReadingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Reading).
func (m *ReadingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ReadingMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, reading.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, reading.FieldUpdatedAt)
	}
	if m.blog_id != nil {
		fields = append(fields, reading.FieldBlogID)
	}
	if m.reading_count != nil {
		fields = append(fields, reading.FieldReadingCount)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ReadingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case reading.FieldCreatedAt:
		return m.CreatedAt()
	case reading.FieldUpdatedAt:
		return m.UpdatedAt()
	case reading.FieldBlogID:
		return m.BlogID()
	case reading.FieldReadingCount:
		return m.ReadingCount()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ReadingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case reading.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case reading.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case reading.FieldBlogID:
		return m.OldBlogID(ctx)
	case reading.FieldReadingCount:
		return m.OldReadingCount(ctx)
	}
	return nil, fmt.Errorf("unknown Reading field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReadingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case reading.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case reading.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case reading.FieldBlogID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlogID(v)
		return nil
	case reading.FieldReadingCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetReadingCount(v)
		return nil
	}
	return fmt.Errorf("unknown Reading field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ReadingMutation) AddedFields() []string {
	var fields []string
	if m.addreading_count != nil {
		fields = append(fields, reading.FieldReadingCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ReadingMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case reading.FieldReadingCount:
		return m.AddedReadingCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReadingMutation) AddField(name string, value ent.Value) error {
	switch name {
	case reading.FieldReadingCount:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddReadingCount(v)
		return nil
	}
	return fmt.Errorf("unknown Reading numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ReadingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ReadingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ReadingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Reading nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ReadingMutation) ResetField(name string) error {
	switch name {
	case reading.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case reading.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case reading.FieldBlogID:
		m.ResetBlogID()
		return nil
	case reading.FieldReadingCount:
		m.ResetReadingCount()
		return nil
	}
	return fmt.Errorf("unknown Reading field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ReadingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ReadingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ReadingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ReadingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ReadingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ReadingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ReadingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Reading unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ReadingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Reading edge %s", name)
}
