// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/data/ent/predicate"
	"github.com/DrReMain/cyber-ecosystem/examples/template2/internal/data/ent/reading"
)

// ReadingUpdate is the builder for updating Reading entities.
type ReadingUpdate struct {
	config
	hooks     []Hook
	mutation  *ReadingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ReadingUpdate builder.
func (_u *ReadingUpdate) Where(ps ...predicate.Reading) *ReadingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingUpdate) SetUpdatedAt(v time.Time) *ReadingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogID sets the "blog_id" field.
func (_u *ReadingUpdate) SetBlogID(v string) *ReadingUpdate {
	_u.mutation.SetBlogID(v)
	return _u
}

// SetNillableBlogID sets the "blog_id" field if the given value is not nil.
func (_u *ReadingUpdate) SetNillableBlogID(v *string) *ReadingUpdate {
	if v != nil {
		_u.SetBlogID(*v)
	}
	return _u
}

// SetReadingCount sets the "reading_count" field.
func (_u *ReadingUpdate) SetReadingCount(v int64) *ReadingUpdate {
	_u.mutation.ResetReadingCount()
	_u.mutation.SetReadingCount(v)
	return _u
}

// SetNillableReadingCount sets the "reading_count" field if the given value is not nil.
func (_u *ReadingUpdate) SetNillableReadingCount(v *int64) *ReadingUpdate {
	if v != nil {
		_u.SetReadingCount(*v)
	}
	return _u
}

// AddReadingCount adds value to the "reading_count" field.
func (_u *ReadingUpdate) AddReadingCount(v int64) *ReadingUpdate {
	_u.mutation.AddReadingCount(v)
	return _u
}

// Mutation returns the ReadingMutation object of the builder.
func (_u *ReadingUpdate) Mutation() *ReadingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReadingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReadingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reading.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingUpdate) check() error {
	if v, ok := _u.mutation.BlogID(); ok {
		if err := reading.BlogIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_id", err: fmt.Errorf(`ent: validator failed for field "Reading.blog_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReadingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReadingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReadingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reading.Table, reading.Columns, sqlgraph.NewFieldSpec(reading.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reading.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlogID(); ok {
		_spec.SetField(reading.FieldBlogID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadingCount(); ok {
		_spec.SetField(reading.FieldReadingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadingCount(); ok {
		_spec.AddField(reading.FieldReadingCount, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReadingUpdateOne is the builder for updating a single Reading entity.
type ReadingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ReadingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingUpdateOne) SetUpdatedAt(v time.Time) *ReadingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBlogID sets the "blog_id" field.
func (_u *ReadingUpdateOne) SetBlogID(v string) *ReadingUpdateOne {
	_u.mutation.SetBlogID(v)
	return _u
}

// SetNillableBlogID sets the "blog_id" field if the given value is not nil.
func (_u *ReadingUpdateOne) SetNillableBlogID(v *string) *ReadingUpdateOne {
	if v != nil {
		_u.SetBlogID(*v)
	}
	return _u
}

// SetReadingCount sets the "reading_count" field.
func (_u *ReadingUpdateOne) SetReadingCount(v int64) *ReadingUpdateOne {
	_u.mutation.ResetReadingCount()
	_u.mutation.SetReadingCount(v)
	return _u
}

// SetNillableReadingCount sets the "reading_count" field if the given value is not nil.
func (_u *ReadingUpdateOne) SetNillableReadingCount(v *int64) *ReadingUpdateOne {
	if v != nil {
		_u.SetReadingCount(*v)
	}
	return _u
}

// AddReadingCount adds value to the "reading_count" field.
func (_u *ReadingUpdateOne) AddReadingCount(v int64) *ReadingUpdateOne {
	_u.mutation.AddReadingCount(v)
	return _u
}

// Mutation returns the ReadingMutation object of the builder.
func (_u *ReadingUpdateOne) Mutation() *ReadingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReadingUpdate builder.
func (_u *ReadingUpdateOne) Where(ps ...predicate.Reading) *ReadingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReadingUpdateOne) Select(field string, fields ...string) *ReadingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Reading entity.
func (_u *ReadingUpdateOne) Save(ctx context.Context) (*Reading, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingUpdateOne) SaveX(ctx context.Context) *Reading {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReadingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reading.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingUpdateOne) check() error {
	if v, ok := _u.mutation.BlogID(); ok {
		if err := reading.BlogIDValidator(v); err != nil {
			return &ValidationError{Name: "blog_id", err: fmt.Errorf(`ent: validator failed for field "Reading.blog_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ReadingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ReadingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ReadingUpdateOne) sqlSave(ctx context.Context) (_node *Reading, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reading.Table, reading.Columns, sqlgraph.NewFieldSpec(reading.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Reading.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reading.FieldID)
		for _, f := range fields {
			if !reading.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reading.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BlogID(); ok {
		_spec.SetField(reading.FieldBlogID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadingCount(); ok {
		_spec.SetField(reading.FieldReadingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReadingCount(); ok {
		_spec.AddField(reading.FieldReadingCount, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Reading{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
