// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file desc/desc.proto (package desc, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions, ServiceOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file desc/desc.proto.
 */
export const file_desc_desc: GenFile = /*@__PURE__*/
  fileDesc("Cg9kZXNjL2Rlc2MucHJvdG8SBGRlc2M6SgoPc2VydmljZV9jb21tZW50Eh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGKGcASABKAlSDnNlcnZpY2VDb21tZW50OkcKDm1ldGhvZF9jb21tZW50Eh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMYseoBIAEoCVINbWV0aG9kQ29tbWVudEIoWiZjeWJlci1lY29zeXN0ZW0vY29udHJhY3RzL2dvL2Rlc2M7ZGVzY2IGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: string service_comment = 20001;
 */
export const service_comment: GenExtension<ServiceOptions, string> = /*@__PURE__*/
  extDesc(file_desc_desc, 0);

/**
 * @generated from extension: string method_comment = 30001;
 */
export const method_comment: GenExtension<MethodOptions, string> = /*@__PURE__*/
  extDesc(file_desc_desc, 1);

