apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitchtip
  namespace: observability
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: GLITCHTIP_DOMAIN
              value: http://errors.example.com
        - name: worker
          env:
            - name: GLITCHTIP_DOMAIN
              value: http://errors.example.com
