apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: seaweedfs
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: s3.example.com
  - target:
      kind: Ingress
      name: centrifugo
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: realtime.example.com
  - target:
      kind: Ingress
      name: livekit
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: rtc.example.com
  - target:
      kind: Ingress
      name: signoz
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: observe.example.com
  - target:
      kind: Ingress
      name: glitchtip
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: errors.example.com
  - target:
      kind: Ingress
      name: signoz-otel-collector
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: otlp.example.com
  - path: glitchtip-deployment.yaml
  - path: glitchtip-job.yaml
